// Definición del documento Formato Servicios (Glosas de Requerimientos):
// orden y correlativos exactos según el documento adjunto.
// kind: 'numero' | 'heading' | 'tabla_entregas' | 'tabla_informacion' | 'firmas'
export const MODELO_SERVICIOS = [
  // ===== 4.2 al 7 — SIN CAMBIOS =====
  { key: '4.2', kind: 'numero', label: '4.2', type: 'textarea', titulo: 'CARACTERÍSTICAS TÉCNICAS DEL SERVICIO', helper: '(Indicar el detalle de las actividades a desarrollar)', default: 'Las características técnicas del presente servicio consisten en: \n\nxxxxxxxx.\nxxxxxxxx.' },
  { key: '5', kind: 'numero', label: '5', type: 'textarea', titulo: 'REQUISITOS DEL PROVEEDOR', helper: '(Precisar las características o condiciones mínimas que debe cumplir el proveedor, sea persona natural o jurídica)', default: 'Xxxxxxxxx\nxxxxxxxx' },
  { key: '5.1', kind: 'numero', label: '5.1', type: 'textarea', titulo: 'EXPERIENCIA DEL PROVEEDOR', default: 'El postor debe acreditar un monto facturado acumulado equivalente a [CONSIGNAR EL MONTO DE FACTURACIÓN EXPRESADO EN NÚMEROS Y LETRAS EN LA MONEDA DE LA CONTRATACIÓN, MONTO QUE NO PODRÁ SER MAYOR A TRES VECES LA CUANTÍA DE LA CONTRATACIÓN O DEL ÍTEM], por la contratación de servicios iguales o similares al objeto de la convocatoria, durante los quince años anteriores a la fecha de la presentación de ofertas que se computa desde la fecha de la conformidad o emisión del comprobante de pago, según corresponda.\n\nSe consideran servicios similares a los siguientes [CONSIGNAR LOS SERVICIOS SIMILARES AL OBJETO CONTRATADO].\n\nAcreditación:\nLa experiencia del proveedor en la especialidad se acredita con un máximo de veinte (20) contrataciones, mediante copia simple de: (i) contratos u órdenes de servicios, y su respectiva conformidad o constancia de prestación; o (ii) comprobantes de pago cuya cancelación se acredite documental y fehacientemente.' },
  { key: '5.2', kind: 'numero', label: '5.2', type: 'textarea', titulo: 'REQUISITOS ADICIONALES PARA LA CONTRATACIÓN', default: 'Cotización / propuesta económica.\nRegistro Nacional de Proveedores (RNP), vigente.\nConsulta RUC, activo.\nDeclaración Jurada de no estar inhabilitado de contratar con el estado y de no tener parentesco.\nFormato CCI enlazado al RUC.' },
  { key: '6', kind: 'numero', label: '6', type: 'textarea', titulo: 'GARANTÍA', helper: '(De corresponder, detallar la garantía del servicio o en su defecto indicar: No corresponde)', default: 'No corresponde.' },
  { key: '7', kind: 'numero', label: '7', type: 'textarea', titulo: 'SEGURO', default: 'En la contratación del servicio se debe solicitar la presentación del seguro contra accidentes personales o seguro complementario de trabajo de riesgo (pensión, salud) o ESSALUD ó SIS.' },

  // ===== 8 — OTRAS CLÁUSULAS (heading) =====
  { key: '8', kind: 'heading', label: '8', titulo: 'OTRAS CLÁUSULAS' },
  { key: '8.1', kind: 'numero', label: '8.1', type: 'textarea', titulo: 'SEGURIDAD DE LA INFORMACIÓN DE LA ENTIDAD', helper: '(De requerir en el requerimiento, el contratista se compromete a respetar y aplicar en el servicio brindado, los lineamientos de Seguridad de la Información con Proveedores del INS)', default: 'De requerir en el requerimiento, el contratista se compromete a respetar y aplicar en el servicio brindado, los lineamientos de Seguridad de la Información con Proveedores del INS, los mismos que declara conocer y aceptar. Asimismo, para el inicio efectivo del servicio el contratista deberá de presentar la siguiente documentación: Compromiso de confidencialidad y no divulgación de información del INS. Constancia de recepción de lineamiento de seguridad de la información.' },
  { key: '8.2', kind: 'numero', label: '8.2', type: 'textarea', titulo: 'CLÁUSULA ANTICORRUPCIÓN Y ANTISOBORNO', default: 'Al notificarse la orden o suscribir el contrato, EL CONTRATISTA declara y garantiza no haber ofrecido, negociado, prometido o efectuado ningún pago o entrega de cualquier beneficio o incentivo ilegal, de manera directa o indirecta, a los evaluadores del proceso de contratación o cualquier servidor de la entidad contratante.\n\nAsimismo, EL CONTRATISTA se obliga a mantener una conducta proba e íntegra durante la vigencia del contrato, y después de culminado el mismo en caso existan controversias pendientes de resolver, lo que supone actuar con probidad, sin cometer actos ilícitos, directa o indirectamente.\n\nAunado a ello, EL CONTRATISTA se obliga a abstenerse de ofrecer, negociar, prometer o dar regalos, cortesías, invitaciones, donativos o cualquier beneficio o incentivo ilegal, directa o indirectamente, a funcionarios públicos, servidores públicos, locadores de servicios o proveedores de servicios del área usuaria, de la dependencia encargada de la contratación, actores del proceso de contratación y/o cualquier servidor de la entidad contratante, con la finalidad de obtener alguna ventaja indebida o beneficio ilícito.\n\nAdicionalmente, EL CONTRATISTA se compromete a denunciar oportunamente ante las autoridades competentes los actos de corrupción o de inconducta funcional de los cuales tuviera conocimiento durante la ejecución del contrato con LA ENTIDAD CONTRATANTE.\n\nFinalmente, el incumplimiento de las obligaciones establecidas en esta cláusula, durante la ejecución contractual, otorga a LA ENTIDAD CONTRATANTE el derecho de resolver total o parcialmente el contrato.' },
  { key: '8.3', kind: 'numero', label: '8.3', type: 'textarea', titulo: 'CLÁUSULA DE CONFIDENCIALIDAD Y PROPIEDAD INTELECTUAL', default: 'El contratista se compromete a mantener en reserva y a no revelar a terceros, sin previa autorización escrita del INS, toda información que le sea suministrada por ésta última y/o sea obtenida en el ejercicio de las actividades a desarrollarse o conozca directa o indirectamente para la realización de sus tareas, excepto en cuanto resulte estrictamente necesario para el cumplimiento de la Orden de Compra y/o Servicio, en adelante el contrato. El contratista deberá mantener a perpetuidad la confidencialidad y reserva absoluta en el manejo de cualquier información y documentación a la que se tenga acceso a consecuencia de la ejecución del contrato, quedando prohibida revelar a terceros. Dicha obligación comprende la información que se entrega, como también la que se genera durante la realización de las actividades previas a la ejecución del contrato, durante su ejecución y la producida una vez que se haya concluido el contrato. Los documentos técnicos, estudios, informes, grabaciones, programas informáticos y todos los demás que formen parte de su cotización y su propuesta y que se deriven de las prestaciones contratadas serán de exclusiva propiedad del INS.' },
  { key: '8.4', kind: 'numero', label: '8.4', type: 'textarea', titulo: 'CLÁUSULA DE CUMPLIMIENTO (Ley N° 31564)', default: '"Son causales de resolución de contrato la presentación con información inexacta o falsa de la Declaración Jurada de Prohibiciones e Incompatibilidades a que se hace referencia en la Ley de prevención y mitigación del conflicto de intereses en el acceso y salida de personal del servicio público. Asimismo, en caso se incumpla con los impedimentos señalados en el artículo 5° de dicha Ley se aplicará la inhabilitación por cinco años para contratar o prestar servicios al Estado, bajo cualquier modalidad."' },
  { key: '8.5', kind: 'numero', label: '8.5', type: 'textarea', titulo: 'SOLUCIÓN DE CONTROVERSIA', default: 'Todos los conflictos que se deriven de la ejecución e interpretación de la presente contratación, son resueltos mediante trato directo, conciliación y/o acción judicial.' },
  { key: '8.6', kind: 'numero', label: '8.6', type: 'textarea', titulo: 'VICIOS OCULTOS', default: 'La recepción conforme de la prestación por parte de LA ENTIDAD CONTRATANTE no enerva su derecho a reclamar posteriormente por defectos o vicios ocultos, conforme a lo dispuesto por los artículos 69 de la Ley N° 32069, Ley General de Contrataciones Públicas y 144 de su Reglamento aprobado por Decreto Supremo N° 009-2025-EF.\n\nEl plazo máximo de responsabilidad del contratista es de un (01) año contado a partir de la conformidad otorgada por LA ENTIDAD CONTRATANTE.' },
  { key: '8.7', kind: 'numero', label: '8.7', type: 'textarea', titulo: 'GESTIÓN DE RIESGOS', default: 'Al no realizarse segmentación de contrataciones para contratos menores, no corresponde determinar una matriz de riesgos.' },
  { key: '8.8', kind: 'numero', label: '8.8', type: 'textarea', titulo: 'SOBRE LA DECLARACIÓN JURADA DE INTERESES', default: 'Conforme al artículo 3 de la Ley Nº 31227, las personas que participen en las actividades señaladas en dicho artículo se encuentran obligadas a presentar la declaración jurada de intereses; obligación que será exigible, de acuerdo a lo establecido en el Sistema de Declaraciones Juradas para la Gestión de Conflictos de Intereses de la Contraloría General de la República, de corresponder.' },
  { key: '8.9', kind: 'numero', label: '8.9', type: 'textarea', titulo: 'CAUSALES DE RESOLUCIÓN DE CONTRATO', default: 'Se resuelve el contrato en los siguientes casos:\na) Cuando el/la contratista incumpla injustificadamente obligaciones contractuales, legales o reglamentarias a sus actividades, pese a haber sido requerido para ello.\nb) Cuando el/la contratista acumule el monto máximo de la penalidad por mora o el monto máximo por otras penalidades, en la ejecución de la prestación.\nc) Cuando el/la contratista paralice o reduzca injustificadamente la ejecución de la prestación, pese a haber sido requerido para corregir tal situación.\nd) Por incumplimiento de la cláusula anticorrupción y antisoborno.\ne) Por la presentación de documentación falsa o inexacta durante la ejecución contractual.\nf) Cualquiera de las partes puede resolver el contrato por caso fortuito, fuerza mayor, por hecho sobreviniente al perfeccionamiento del contrato que no sea imputable a las partes y que imposibilite de manera definitiva la continuación de la ejecución del contrato.\ng) Por la presentación con información inexacta o falsa de la Declaración Jurada de Prohibiciones e Incompatibilidades a que se hace referencia en la Ley N° 31564.\nh) Por mutuo acuerdo entre las partes, de forma parcial o total, previa opinión del área usuaria.' },

  // ===== 9 — PLAZO, ENTREGABLES, MODALIDAD Y CONDICIONES DE PAGO =====
  { key: '9', kind: 'heading', label: '9', titulo: 'PLAZO, ENTREGABLES, MODALIDAD Y CONDICIONES DE PAGO' },
  { key: '9.1', kind: 'numero', label: '9.1', type: 'textarea', titulo: 'PLAZO DE REALIZACIÓN DEL SERVICIO', default: 'El plazo de ejecución del servicio será realizado hasta los xxx (xx) días calendario, contados desde el día siguiente de notificada la orden de servicio. (Contemplar aquí el plazo total del servicio)\n\nEl servicio se realizará en las instalaciones de xxxxxxxxxxxxxxxx, de forma presencial / híbrido / remoto.' },
  { key: '9.2', kind: 'numero', label: '9.2', type: 'textarea', titulo: 'ENTREGABLES', default: '(De corresponder, detallar el número de entregables, el contenido de cada entregable, los plazos de presentación y condiciones relevantes para cumplir con cada entregable)\n\nEl presente servicio será ejecutado con xxx entregables y cada entregable será sustentado por un informe emitido por el proveedor adjudicado, en virtud de lo señalado en el numeral 4.2, Anexando el siguiente detalle:\n\n(se deberá precisar si es un único entregable o en su defecto detallar cuantos entregables posee el servicio en mención).' },
  { key: '9.2.1', kind: 'tabla_entregas', label: '9.2.1', titulo: 'N° DE ENTREGABLES' },
  { key: '9.2.2', kind: 'tabla_informacion', label: '9.2.2', titulo: 'PLAZO PARA PRESENTAR ENTREGABLES' },

  // ===== 10 al 16 — separados =====
  { key: '10', kind: 'numero', label: '10', type: 'textarea', titulo: 'MODALIDAD DE PAGO', default: 'Suma alzada' },
  { key: '11', kind: 'numero', label: '11', type: 'textarea', titulo: 'CONDICIONES DE PAGO', default: 'Pago periódico / único, conforme a lo establecido en el numeral 9.2 y considerando la oferta económica del proveedor adjudicado.\n\n(Precisar si se realiza el pago de la contraprestación en un solo pago o pagos periódicos. Precisar la documentación obligatoria a presentar por el proveedor para la realización del pago)' },
  { key: '12', kind: 'numero', label: '12', type: 'textarea', titulo: 'DOCUMENTACIÓN OBLIGATORIA PARA EL PAGO', default: '• Carta de presentación del entregable.\n• Informe de actividades.\n• Comprobante de pago.\n• Formato CCI enlazado al RUC.\n• Seguro particular, SCTR, ESSALUD o SIS (de corresponder).' },
  { key: '13', kind: 'numero', label: '13', type: 'textarea', titulo: 'CONFORMIDAD DE LA PRESTACIÓN', default: 'El área usuaria emitirá el Acta de Conformidad del cumplimiento del servicio, la cual debe ser suscrita obligatoriamente por el área usuaria y el director general, en caso de investigaciones será otorgada por el Investigador Principal o coinvestigador del proyecto de investigación.' },
  { key: '14', kind: 'numero', label: '14', type: 'textarea', titulo: 'PENALIDAD', default: 'En caso de retraso injustificado en la ejecución de las prestaciones objeto del contrato menor, la entidad contratante le aplica al proveedor una penalidad por cada día de atraso que le sea imputable, hasta por un monto máximo equivalente al 10% del monto de la contratación o ítem correspondiente, que puede descontarse del pago del entregable o del pago final. En todos los casos, la penalidad se aplica automáticamente y se calcula de acuerdo con la siguiente fórmula:\n\nPenalidad diaria = 0.10 x Monto de la contratación o ítem / F x Plazo en días del entregable\nF = 0.40\n\nUna vez que se llega al monto máximo de la penalidad por mora, la entidad contratante puede optar por resolver el contrato menor.' },
  { key: '15', kind: 'numero', label: '15', type: 'textarea', titulo: 'OTRAS PENALIDADES', helper: '(De acuerdo al tipo de contratación las áreas usuarias pueden establecer otras penalidades diferentes a la mora)', default: '' },
  { key: '16', kind: 'numero', label: '16', type: 'textarea', titulo: 'OTROS', default: 'No aplica.' },

  // ===== Firmas =====
  { key: 'firmas', kind: 'firmas' },
];