/**
 * Catálogo de acciones y tipos de evento del SGC Core.
 */

export const ACCIONES = Object.freeze({
  CREADO: 'CREADO',
  EDITADO: 'EDITADO',
  APROBADO: 'APROBADO',
  RECHAZADO: 'RECHAZADO',
  OBSERVADO: 'OBSERVADO',
  SUBSANADO: 'SUBSANADO',
  DERIVADO: 'DERIVADO',
  REENVIADO: 'REENVIADO',
  FIRMADO: 'FIRMADO',
  DESCARGADO: 'DESCARGADO',
  EXPORTADO: 'EXPORTADO',
  ANULADO: 'ANULADO',
  FINALIZADO: 'FINALIZADO',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
});

export const TIPOS_OPERACION_AUDITORIA = Object.freeze({
  INSERT: 'INSERT',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
});

export const TIPOS_ADJUNTO = Object.freeze({
  DOCUMENTO: 'DOCUMENTO',
  PDF: 'PDF',
  EXCEL: 'EXCEL',
  IMAGEN: 'IMAGEN',
  WORD: 'WORD',
  OTROS: 'OTROS',
});

export const ENTIDADES_ADJUNTABLES = Object.freeze({
  EXPEDIENTE: 'EXPEDIENTE',
  OBSERVACION: 'OBSERVACION',
  SOLICITUD_COTIZACION: 'SOLICITUD_COTIZACION',
  PROVEEDOR: 'PROVEEDOR',
  VALIDACION: 'VALIDACION',
  CONTRATO: 'CONTRATO',
});

export const TIPOS_EVENTO_TIMELINE = Object.freeze({
  ETAPA: 'ETAPA',
  OBSERVACION: 'OBSERVACION',
  SUBSANACION: 'SUBSANACION',
  DERIVACION: 'DERIVACION',
  AUDITORIA: 'AUDITORIA',
  ADJUNTO: 'ADJUNTO',
});

export default { ACCIONES, TIPOS_OPERACION_AUDITORIA, TIPOS_ADJUNTO, ENTIDADES_ADJUNTABLES, TIPOS_EVENTO_TIMELINE };
