// Migración: Crear tabla carreras_profesionales y sembrar datos iniciales
// Los datos provienen del archivo lista de carreras profesionales.xlsx

export default `
  -- Insertar carreras profesionales desde el listado del Excel
  INSERT INTO carreras_profesionales (nombre_carrera, tipo_carrera)
  SELECT * FROM (VALUES
    ('Acuicultura', 'Profesional'),
    ('Acuicultura y Gerenciamiento', 'Profesional'),
    ('Adicciones y Conductas Adictivas', 'Profesional'),
    ('Administración', 'Profesional'),
    ('Administración Bancaria y Financiera', 'Profesional'),
    ('Administración con Mención en Dirección de Empresas', 'Profesional'),
    ('Administración con mención en Gestión Empresarial', 'Profesional'),
    ('Administración de Banca y Finanzas', 'Profesional'),
    ('Administración de Empresas', 'Profesional'),
    ('Administración de Empresas y Marketing', 'Profesional'),
    ('Administración de Empresas y Negocios Internacionales', 'Profesional'),
    ('Administración de Empresas y Servicios', 'Profesional'),
    ('Administración de Hotelería y Turismo', 'Profesional'),
    ('Administración de la Energía', 'Profesional'),
    ('Administración de la Gastronomía', 'Profesional'),
    ('Administración de la Salud', 'Profesional'),
    ('Administración de Negocios', 'Profesional'),
    ('Administración de Negocios Digitales', 'Profesional'),
    ('Administración de Negocios Globales', 'Profesional'),
    ('Administración de Negocios Globales de Energía y Minería', 'Profesional'),
    ('Administración de Negocios Hoteleros y Turísticos', 'Profesional'),
    ('Administración de Negocios Internacionales', 'Profesional'),
    ('Administración de Negocios y Finanzas', 'Profesional'),
    ('Administración de Negocios y Marketing', 'Profesional'),
    ('Administración de Recursos Humanos', 'Profesional'),
    ('Administración de Servicios', 'Profesional'),
    ('Administración de Turismo', 'Profesional'),
    ('Administración de Turismo Sostenible y Hotelería', 'Profesional'),
    ('Administración de Turismo y Hotelería', 'Profesional'),
    ('Administración e Innovación Empresarial', 'Profesional'),
    ('Administración e Innovación Social', 'Profesional'),
    ('Administración e Inteligencia de Negocios', 'Profesional'),
    ('Administración Educativa y Desarrollo Sostenible', 'Profesional'),
    ('Administración en Salud', 'Profesional'),
    ('Administración en Turismo', 'Profesional'),
    ('Administración en Turismo y Hotelería', 'Profesional'),
    ('Administración Estratégica de Empresas', 'Profesional'),
    ('Administración Estratégica de Negocios Alimentarios Globales', 'Profesional'),
    ('Administración Estratégica de Negocios Jurídicos', 'Profesional'),
    ('Administración Hotelera', 'Profesional'),
    ('Administración Hotelera y de Servicios Turísticos', 'Profesional'),
    ('Administración Hotelera y de Turismo', 'Profesional'),
    ('Administración Hotelera y Turismo', 'Profesional'),
    ('Administración Marítima y Portuaria', 'Profesional'),
    ('Administración Marítima, Portuaria y Pesquera', 'Profesional'),
    ('Administración Portuaria y de Transporte Intermodal', 'Profesional'),
    ('Administración Pública', 'Profesional'),
    ('Administración Turística', 'Profesional'),
    ('Administración Turístico - Hotelera', 'Profesional'),
    ('Administración y Agronegocios', 'Profesional'),
    ('Administración y Business Analytics', 'Profesional'),
    ('Administración y Ciencia de Datos', 'Profesional'),
    ('Administración y Ciencia de Datos para Negocios', 'Profesional'),
    ('Administración y Ciencias Policiales', 'Profesional'),
    ('Administración y Ciencias Policiales con Mención en Gestión Pública', 'Profesional'),
    ('Administración y Contabilidad', 'Profesional'),
    ('Administración y Dirección de Empresas', 'Profesional'),
    ('Administración y Diseño de Servicios', 'Profesional'),
    ('Administración y Emprendimiento', 'Profesional'),
    ('Administración y Emprendimiento Empresarial', 'Profesional'),
    ('Administración y Finanzas', 'Profesional'),
    ('Administración y Finanzas Corporativas', 'Profesional'),
    ('Administración y Gerencia', 'Profesional'),
    ('Administración y Gerencia de Los Servicios de Salud', 'Profesional'),
    ('Administración y Gerencia del Emprendimiento', 'Profesional'),
    ('Administración y Gerencia en Salud', 'Profesional'),
    ('Administración y Gestión Ambiental', 'Profesional'),
    ('Administración y Gestión Comercial', 'Profesional'),
    ('Administración y Gestión de Negocios Internacionales y Aduanas', 'Profesional'),
    ('Administración y Gestión del Capital Humano', 'Profesional'),
    ('Administración y Gestión del Emprendimiento', 'Profesional'),
    ('Administración y Gestión del Talento Humano', 'Profesional'),
    ('Administración y Gestión Empresarial', 'Profesional'),
    ('Administración y Gestión en Salud', 'Profesional'),
    ('Administración y Gestión Pública', 'Profesional'),
    ('Administración y Marketing', 'Profesional'),
    ('Administración y Negocios del Deporte', 'Profesional'),
    ('Administración y Negocios Digitales', 'Profesional'),
    ('Administración y Negocios Globales', 'Profesional'),
    ('Administración y Negocios Internacionales', 'Profesional'),
    ('Administración y Negocios Sostenibles', 'Profesional'),
    ('Administración y Políticas Públicas', 'Profesional'),
    ('Administración y Recursos Humanos', 'Profesional'),
    ('Administración y Servicios Turísticos', 'Profesional'),
    ('Administración y Sistemas', 'Profesional'),
    ('Administración y Talento Humano', 'Profesional'),
    ('Administración, Banca y Finanzas', 'Profesional'),
    ('Adolescentología', 'Profesional'),
    ('Adulto Mayor y Geriatría', 'Profesional'),
    ('Agricultura Sustentable', 'Profesional'),
    ('Agroindustrias', 'Profesional'),
    ('Agronegocios', 'Profesional'),
    ('Agronomía', 'Profesional'),
    ('Agronomía Tropical', 'Profesional'),
    ('Agronomía y Negocios', 'Profesional'),
    ('Alta Dirección y Seguridad Nacional', 'Profesional'),
    ('Alto Riesgo en Obstetricia', 'Profesional'),
    ('Alto Riesgo Obstétrico', 'Profesional'),
    ('Alto Riesgo Obstétrico y Emergencias Obstétricas', 'Profesional'),
    ('Altos Estudios Amazónicos', 'Profesional'),
    ('Análisis Bioquímicos Clínicos', 'Profesional'),
    ('Análisis Demográfico', 'Profesional'),
    ('Anatomía Patológica', 'Profesional'),
    ('Andragogía', 'Profesional'),
    ('Anestesiología', 'Profesional'),
    ('Anestesiología Cardiovascular', 'Profesional'),
    ('Anestesiología Obstétrica', 'Profesional'),
    ('Animales de Compañía', 'Profesional'),
    ('Antropología', 'Profesional'),
    ('Antropología con Mención en Estudios Andinos', 'Profesional'),
    ('Antropología Forense y Bioarqueología', 'Profesional'),
    ('Antropología Social', 'Profesional'),
    ('Antropología Visual', 'Profesional'),
    ('Arbitraje y Conciliación', 'Profesional'),
    ('Arbitraje y Contrataciones con el Estado', 'Profesional'),
    ('Archivística y Gestión Documental', 'Profesional'),
    ('Arqueología', 'Profesional'),
    ('Arqueología Andina', 'Profesional'),
    ('Arqueología Aplicada', 'Profesional'),
    ('Arqueología con Mención en Estudios Andinos', 'Profesional'),
    ('Arqueología e Historia', 'Profesional'),
    ('Arquitectura', 'Profesional'),
    ('Arquitectura de Interiores', 'Profesional'),
    ('Arquitectura y Diseño de Interiores', 'Profesional'),
    ('Arquitectura y Gestion de Proyectos', 'Profesional'),
    ('Arquitectura y Procesos Proyectuales', 'Profesional'),
    ('Arquitectura y Urbanismo', 'Profesional'),
    ('Arquitectura y Urbanismo Ambiental', 'Profesional'),
    ('Arquitectura, Urbanismo y Desarrollo Territorial Sostenible', 'Profesional'),
    ('Arquitectura, Urbanismo y Estudios Territoriales', 'Profesional'),
    ('Arquitectura, Urbanismo y Territorio', 'Profesional'),
    ('Arte', 'Profesional'),
    ('Arte & Diseño Gráfico Empresarial', 'Profesional'),
    ('Arte con especialidad en Artes Plásticas', 'Profesional'),
    ('Arte con especialidad en Danzas', 'Profesional'),
    ('Arte con especialidad en Música', 'Profesional'),
    ('Arte con especialidad en Pedagogía Artística', 'Profesional'),
    ('Arte con especialidad en Teatro', 'Profesional'),
    ('Arte Culinario', 'Profesional'),
    ('Arte y Diseño Empresarial', 'Profesional'),
    ('Arte, Moda y Diseño Textil', 'Profesional'),
    ('Arte: Artes Plásticas', 'Profesional'),
    ('Arte: Danza', 'Profesional'),
    ('Arte: Música', 'Profesional'),
    ('Arte: Teatro', 'Profesional'),
    ('Artes', 'Profesional'),
    ('Artes & Diseño Gráfico Empresarial', 'Profesional'),
    ('Artes con Especialidad de Música', 'Profesional'),
    ('Artes con Especialidad de Plásticas', 'Profesional'),
    ('Artes Escénicas', 'Profesional'),
    ('Artes Escénicas y Literatura', 'Profesional'),
    ('Artes Liberales con Mención en Filosofía', 'Profesional'),
    ('Artes Liberales con Mención en Historia', 'Profesional'),
    ('Artes Plásticas', 'Profesional'),
    ('Artes Plásticas y Visuales con Especialidad Conservación y Restauración', 'Profesional'),
    ('Artes Plásticas y Visuales con Especialidad en Cerámica', 'Profesional'),
    ('Artes Plásticas y Visuales con Especialidad en Escultura', 'Profesional'),
    ('Artes Plásticas y Visuales con Especialidad en Grabado', 'Profesional'),
    ('Artes Plásticas y Visuales con Especialidad en Pintura', 'Profesional'),
    ('Artes Visuales con Especialidad en Dibujo y Cerámica', 'Profesional'),
    ('Artes Visuales con Especialidad en Dibujo y Escultura', 'Profesional'),
    ('Artes Visuales con Especialidad en Dibujo y Grabado y Diseño Gráfico', 'Profesional'),
    ('Artes Visuales con Especialidad en Dibujo y Pintura', 'Profesional'),
    ('Artes Visuales con Mención en Acuarela', 'Profesional'),
    ('Artes Visuales con Mención en Cerámica', 'Profesional'),
    ('Artes Visuales con Mención en Escultura', 'Profesional'),
    ('Artes Visuales con Mención en Pintura', 'Profesional'),
    ('Artista Músico con Especialidad en Composición', 'Profesional'),
    ('Artista Músico con Especialidad en Ejecución Instrumental y Canto', 'Profesional'),
    ('Artista Profesional – Especialidad: Actuación Teatral', 'Profesional'),
    ('Artista Profesional Artes Plásticas y Visuales', 'Profesional'),
    ('Artista Profesional Artes Plásticas y Visuales, Mención Escultura', 'Profesional'),
    ('Artista Profesional Artes Plásticas y Visuales, Mención Pintura', 'Profesional'),
    ('Artista Profesional con Especialidad de Música', 'Profesional'),
    ('Artista Profesional con Especialidad en Artes Visuales', 'Profesional'),
    ('Artista Profesional con Especialidad en Escultura', 'Profesional'),
    ('Artista Profesional con Especialidad en Grabado', 'Profesional'),
    ('Artista Profesional con Especialidad en Pintura', 'Profesional'),
    ('Artista Profesional con Especialidad en Producción en Diseño Grafico y Artes Publicitarias', 'Profesional'),
    ('Artista Profesional en Música', 'Profesional'),
    ('Artista Profesional Especialidad de Artes Plásticas', 'Profesional'),
    ('Artista Profesional Especialidad de Danza', 'Profesional'),
    ('Artista Profesional Especialidad de Música', 'Profesional'),
    ('Artista Profesional Especialidad de Teatro', 'Profesional'),
    ('Artista Profesional: Especialidad de Artes Plásticas Y Visuales', 'Profesional'),
    ('Artista Profesional: Interpretación Musical', 'Profesional'),
    ('Artista, Especialidad: Artes Plásticas y Visuales (Pintura, Escultura, Grabado, Cerámica)', 'Profesional'),
    ('Artista, Especialidad: Artista Musico', 'Profesional'),
    ('Atención Al Niño en Edad Temprana', 'Profesional'),
    ('Atención Farmacéutica', 'Profesional'),
    ('Atención Primaria con Mención en Prevención del Cáncer Ginecológico', 'Profesional'),
    ('Atención Primaria de la Salud', 'Profesional'),
    ('Auditoría de Sistemas y Seguridad de Información', 'Profesional'),
    ('Auditoría Empresarial y del Sector Público', 'Profesional'),
    ('Auditoría Financiera', 'Profesional'),
    ('Auditoría Integral', 'Profesional'),
    ('Autoevaluación y Acreditación de Instituciones Educativas', 'Profesional'),
    ('Automatización e Instrumentación', 'Profesional'),
    ('Avicultura', 'Profesional'),
    ('Banca y Finanzas', 'Profesional'),
    ('Banca y Seguros', 'Profesional'),
    ('Bibliotecología e Información', 'Profesional'),
    ('Bibliotecología y Ciencias de la Información', 'Profesional'),
    ('Bienestar Fetal', 'Profesional'),
    ('Biocomercio y Desarrollo Sostenible', 'Profesional'),
    ('Biodiversidad y Gestión de Ecosistemas', 'Profesional'),
    ('Bioestadística', 'Profesional'),
    ('Bioingeniería', 'Profesional'),
    ('Biología', 'Profesional'),
    ('Biología - Biología', 'Profesional'),
    ('Biología - Botánica', 'Profesional'),
    ('Biología - Microbiología - Parasitología', 'Profesional'),
    ('Biología - Pesquería', 'Profesional'),
    ('Biología con mención en Biotecnología', 'Profesional'),
    ('Biología en Acuicultura', 'Profesional'),
    ('Biología Marina', 'Profesional'),
    ('Biología Molecular', 'Profesional'),
    ('Biología Pesquera', 'Profesional'),
    ('Biología y Biotecnología', 'Profesional'),
    ('Biología, Química y Ciencia del Ambiente', 'Profesional'),
    ('Biología: Ecología', 'Profesional'),
    ('Biología: Microbiología y Laboratorio Clínico', 'Profesional'),
    ('Biología: Pesquería', 'Profesional'),
    ('Biología-Microbiología', 'Profesional'),
    ('Biomedicina', 'Profesional'),
    ('Bioquímica', 'Profesional'),
    ('Bioquímica Clínica', 'Profesional'),
    ('Biotecnología', 'Profesional'),
    ('Biotecnología e Ingeniería Genética', 'Profesional'),
    ('Bosques y Gestión de Recursos Forestales', 'Profesional'),
    ('Botánica Tropical', 'Profesional'),
    ('Bromatología', 'Profesional'),
    ('Bromatología y Nutrición', 'Profesional'),
    ('Bromatología y Nutrición Humana', 'Profesional'),
    ('Business Analytics', 'Profesional'),
    ('Cardiología', 'Profesional'),
    ('Cardiología Pediátrica', 'Profesional'),
    ('Carielogía y Endodoncia', 'Profesional'),
    ('Carrera de Administración', 'Profesional'),
    ('Carrera de Arquitectura', 'Profesional'),
    ('Carrera de Artista Profesional en Folklore con mención en Danza', 'Profesional'),
    ('Carrera de Artista Profesional en Folklore con mención en Música', 'Profesional'),
    ('Carrera de Comunicación', 'Profesional'),
    ('Carrera de Contabilidad y Finanzas', 'Profesional'),
    ('Carrera de Derecho', 'Profesional'),
    ('Carrera de Economía', 'Profesional'),
    ('Carrera de Educación Artística en Folklore, mención Danza', 'Profesional'),
    ('Carrera de Educación Artística en Folklore, mención Música', 'Profesional'),
    ('Carrera de Educación Artística, Especialidad Arte Dramático', 'Profesional'),
    ('Carrera de Educación Inicial Intercultural Bilingüe', 'Profesional'),
    ('Carrera de Educación Primaria Intercultural Bilingüe', 'Profesional'),
    ('Carrera de Formación Artística, Especialidad Teatro, Mención Actuación', 'Profesional'),
    ('Carrera de Formación Artística, Especialidad Teatro, Mención Diseño Escenográfico', 'Profesional'),
    ('Carrera de Ingeniería Ambiental', 'Profesional'),
    ('Carrera de Ingeniería Civil', 'Profesional'),
    ('Carrera de Ingeniería de Sistemas', 'Profesional'),
    ('Carrera de Ingeniería Industrial', 'Profesional'),
    ('Carrera de Ingeniería Informática', 'Profesional'),
    ('Carrera de Ingeniería Mecatrónica', 'Profesional'),
    ('Carrera de Marketing', 'Profesional'),
    ('Carrera de Negocios Internacionales', 'Profesional'),
    ('Carrera de Psicología', 'Profesional'),
    ('Carrera Profesional de Administración', 'Profesional'),
    ('Carrera Profesional de Administración en Salud', 'Profesional'),
    ('Carrera Profesional de Artista Profesional Especialidad Artes Plásticas y Visuales, mención: Escultura', 'Profesional'),
    ('Carrera Profesional de Artista Profesional Especialidad Artes Plásticas y Visuales, mención: Grabado - Diseño Gráfico', 'Profesional'),
    ('Carrera Profesional de Artista Profesional Especialidad Artes Plásticas y Visuales, mención: Pintura', 'Profesional'),
    ('Carrera Profesional de Biología', 'Profesional'),
    ('Carrera Profesional de Biología Marina', 'Profesional'),
    ('Carrera Profesional de Biotecnología', 'Profesional'),
    ('Carrera Profesional de Ciencia e Ingeniería de Los Materiales (CIM)', 'Profesional'),
    ('Carrera Profesional de Educación', 'Profesional'),
    ('Carrera Profesional de Educación Artística Especialidad: Artes Plásticas', 'Profesional'),
    ('Carrera profesional de Educación con mención en Ciencia y Tecnología', 'Profesional'),
    ('Carrera profesional de Educación con mención en Ciencias Sociales', 'Profesional'),
    ('Carrera Profesional de Educación con mención en Comunicación', 'Profesional'),
    ('Carrera profesional de Educación con mención en Idiomas Extranjeros', 'Profesional'),
    ('Carrera profesional de Educación Física, Recreación y Deportes', 'Profesional'),
    ('Carrera Profesional de Educación Inicial', 'Profesional'),
    ('Carrera Profesional de Educación Primaria', 'Profesional'),
    ('Carrera Profesional de Enfermería', 'Profesional'),
    ('Carrera Profesional de Estomatología', 'Profesional'),
    ('Carrera Profesional de Farmacia y Bioquímica', 'Profesional'),
    ('Carrera Profesional de Gestión de Desarrollo Global', 'Profesional'),
    ('Carrera Profesional de Idioma Extranjero-Inglés', 'Profesional'),
    ('Carrera Profesional de Ingeniería Acuícola', 'Profesional'),
    ('Carrera Profesional de Ingeniería Ambiental', 'Profesional'),
    ('Carrera Profesional de Ingeniería Biomédica', 'Profesional'),
    ('Carrera Profesional de Ingeniería Industrial', 'Profesional'),
    ('Carrera profesional de Interpretación Musical con Mención en Acordeón', 'Profesional'),
    ('Carrera profesional de Interpretación Musical con Mención en Canto', 'Profesional'),
    ('Carrera profesional de Interpretación Musical con Mención en Clarinete', 'Profesional'),
    ('Carrera profesional de Interpretación Musical con Mención en Contrabajo', 'Profesional'),
    ('Carrera profesional de Interpretación Musical con Mención en Corno', 'Profesional'),
    ('Carrera profesional de Interpretación Musical con Mención en Fagot', 'Profesional'),
    ('Carrera Profesional de Interpretación Musical con Mención en Flauta Traversa', 'Profesional'),
    ('Carrera profesional de Interpretación Musical con Mención en Guitarra', 'Profesional'),
    ('Carrera profesional de Interpretación Musical con Mención en Instrumentos Nativos', 'Profesional'),
    ('Carrera profesional de Interpretación Musical con Mención en Oboe', 'Profesional'),
    ('Carrera profesional de Interpretación Musical con Mención en Percusión', 'Profesional'),
    ('Carrera profesional de Interpretación Musical con Mención en Piano', 'Profesional'),
    ('Carrera profesional de Interpretación Musical con Mención en Saxofón', 'Profesional'),
    ('Carrera profesional de Interpretación Musical con Mención en Trombón', 'Profesional'),
    ('Carrera profesional de Interpretación Musical con Mención en Trompeta', 'Profesional'),
    ('Carrera profesional de Interpretación Musical con Mención en Tuba', 'Profesional'),
    ('Carrera profesional de Interpretación Musical con Mención en Viola', 'Profesional'),
    ('Carrera profesional de Interpretación Musical con Mención en Violín', 'Profesional'),
    ('Carrera profesional de Interpretación Musical con Mención en Violoncello', 'Profesional'),
    ('Carrera Profesional de Medicina', 'Profesional'),
    ('Carrera Profesional de Medicina Humana', 'Profesional'),
    ('Carrera Profesional de Medicina Veterinaria y Zootecnia', 'Profesional'),
    ('Carrera Profesional de Nutrición', 'Profesional'),
    ('Carrera Profesional de Psicología', 'Profesional'),
    ('Carrera Profesional de Química', 'Profesional'),
    ('Carrera Profesional de Salud Pública y Salud Global', 'Profesional'),
    ('Carrera Profesional de Tecnología Médica en la Especialidad de Laboratorio Clínico y Anatomía Patológica', 'Profesional'),
    ('Carrera Profesional de Tecnología Médica en la Especialidad de Radiología', 'Profesional'),
    ('Carrera Profesional de Tecnología Médica en la Especialidad de Terapia de Lenguaje', 'Profesional'),
    ('Carrera Profesional de Tecnología Médica en la Especialidad de Terapia Física y Rehabilitación', 'Profesional'),
    ('Carrera Profesional de Tecnología Médica en la Especialidad de Terapia Ocupacional', 'Profesional'),
    ('Centro Quirúrgico', 'Profesional'),
    ('Ciberseguridad', 'Profesional'),
    ('Ciencia Animal', 'Profesional'),
    ('Ciencia de Alimentos', 'Profesional'),
    ('Ciencia de Datos', 'Profesional'),
    ('Ciencia de Datos e Inteligencia Artificial', 'Profesional'),
    ('Ciencia de Datos para Economía y Ciencias Sociales', 'Profesional'),
    ('Ciencia de Datos para Economía y Ciencias Sociales con mención en Finanzas y Analítica de Negocios', 'Profesional'),
    ('Ciencia de Datos para Economía y Ciencias Sociales con mención en Políticas Públicas', 'Profesional'),
    ('Ciencia de la Computación', 'Profesional'),
    ('Ciencia de Los Alimentos', 'Profesional'),
    ('Ciencia Política', 'Profesional'),
    ('Ciencia Política y Gobernabilidad', 'Profesional'),
    ('Ciencia Política y Gobierno', 'Profesional'),
    ('Ciencia Política y Gobierno con Mención en Gerencia Pública', 'Profesional'),
    ('Ciencia Política y Gobierno con Mención en Instituciones Políticas', 'Profesional'),
    ('Ciencia Política y Gobierno con Mención en Políticas Públicas y Gestión Pública', 'Profesional'),
    ('Ciencia Política y Relaciones Internacionales', 'Profesional'),
    ('Ciencia Política y Relaciones Internacionales con Mención en Política Comparada', 'Profesional'),
    ('Ciencia Política y Relaciones Internacionales con Mención en Relaciones Internacionales', 'Profesional'),
    ('Ciencia y Tecnología de Alimentos', 'Profesional'),
    ('Ciencias Administrativas', 'Profesional'),
    ('Ciencias Administrativas con Mención en Administración', 'Profesional'),
    ('Ciencias Aeroespaciales', 'Profesional'),
    ('Ciencias Aeroespaciales con Especialidad en Defensa Aérea', 'Profesional'),
    ('Ciencias Aeroespaciales con Especialidad en Defensa y Operaciones Especiales', 'Profesional'),
    ('Ciencias Aeroespaciales con Especialidad en Ingeniería Aeronáutica', 'Profesional'),
    ('Ciencias Aeroespaciales con Especialidad en Ingeniería de Sistemas', 'Profesional'),
    ('Ciencias Aeroespaciales con Especialidad en Ingeniería de Sistemas y Armamento', 'Profesional'),
    ('Ciencias Aeroespaciales con Especialidad en Ingeniería Electrónica', 'Profesional'),
    ('Ciencias Aeroespaciales con Especialidad en Ingeniería Fotogramétrica', 'Profesional'),
    ('Ciencias Aeroespaciales con Especialidad en Ingeniería Meteorológica', 'Profesional'),
    ('Ciencias Aeroespaciales con Especialidad en Inteligencia', 'Profesional'),
    ('Ciencias Aeroespaciales con Especialidad en Pilotaje', 'Profesional'),
    ('Ciencias Aeronáuticas', 'Profesional'),
    ('Ciencias Agrarias', 'Profesional'),
    ('Ciencias Ambientales', 'Profesional'),
    ('Ciencias Biológicas', 'Profesional'),
    ('Ciencias Contables', 'Profesional'),
    ('Ciencias Contables y Empresariales', 'Profesional'),
    ('Ciencias Contables y Financieras', 'Profesional'),
    ('Ciencias Contables y Financieras con Mención en Contabilidad y Comercio Global', 'Profesional'),
    ('Ciencias Contables y Financieras con Mención en Finanzas e Inversiones Internacionales', 'Profesional'),
    ('Ciencias Contables y Financieras con Mención en Gestión de Riesgos y Auditoría Integral', 'Profesional'),
    ('Ciencias Contables y Financieras con Mención en Gestión de Riesgos y Auditoría Integral (Virtual: Semipresencial)', 'Profesional'),
    ('Ciencias Contables y Financieras con Mención en Tributación Fiscal y Empresarial', 'Profesional'),
    ('Ciencias Contables y Financieras con Mención en Tributación Fiscal y Empresarial (Virtual: Semipresencial)', 'Profesional'),
    ('Ciencias de Datos', 'Profesional'),
    ('Ciencias de la Actividad Física y del Deporte', 'Profesional'),
    ('Ciencias de la Actividad Física y el Deporte', 'Profesional'),
    ('Ciencias de la Administración Aeroespacial con Especialidad en Defensa Aérea', 'Profesional'),
    ('Ciencias de la Administración Aeroespacial con Especialidad en Defensa y Operaciones Especiales', 'Profesional'),
    ('Ciencias de la Administración Aeroespacial con Especialidad en Ingeniera Fotogramétrica', 'Profesional'),
    ('Ciencias de la Administración Aeroespacial con Especialidad en Ingeniería Aeronáutica', 'Profesional'),
    ('Ciencias de la Administración Aeroespacial con Especialidad en Ingeniería de Sistemas', 'Profesional'),
    ('Ciencias de la Administración Aeroespacial con Especialidad en Ingeniería de Sistemas y Armamento', 'Profesional'),
    ('Ciencias de la Administración Aeroespacial con Especialidad en Ingeniería Electrónica', 'Profesional'),
    ('Ciencias de la Administración Aeroespacial con Especialidad en Ingeniería Meteorológica', 'Profesional'),
    ('Ciencias de la Administración Aeroespacial con Especialidad en Inteligencia', 'Profesional'),
    ('Ciencias de la Administración Aeroespacial con Especialidad en Personal - Abastecimiento - Finanzas', 'Profesional'),
    ('Ciencias de la Administración Aeroespacial con Especialidad en Piloto', 'Profesional'),
    ('Ciencias de la Computación', 'Profesional'),
    ('Ciencias de la Comunicación', 'Profesional'),
    ('Ciencias de la Comunicación con Especialidad en Periodismo', 'Profesional'),
    ('Ciencias de la Comunicación con Especialidad en Relaciones Públicas', 'Profesional'),
    ('Ciencias de la Comunicación Social', 'Profesional'),
    ('Ciencias de la Educación', 'Profesional'),
    ('Ciencias de la Educación en Ciencias Biológicas y Química', 'Profesional'),
    ('Ciencias de la Educación en Educación Artística', 'Profesional'),
    ('Ciencias de la Educación en Educación Física', 'Profesional'),
    ('Ciencias de la Educación en Educación Inicial', 'Profesional'),
    ('Ciencias de la Educación en Educación Primaria', 'Profesional'),
    ('Ciencias de la Educación en Filosofía, Psicología y Ciencias Sociales', 'Profesional'),
    ('Ciencias de la Educación en Historia y Geografía', 'Profesional'),
    ('Ciencias de la Educación en Lengua y Literatura', 'Profesional'),
    ('Ciencias de la Educación en Matemática e Informática', 'Profesional'),
    ('Ciencias de la Educación Nivel Secundaria Especialidad Lengua Inglesa', 'Profesional'),
    ('Ciencias de la Educación, Nivel Primaria', 'Profesional'),
    ('Ciencias de la Educación, Nivel Secundaria Especialidad Historia y Ciencias Sociales', 'Profesional'),
    ('Ciencias de la Educación, Nivel Secundaria Especialidad Matemática y Física', 'Profesional'),
    ('Ciencias de la Educación. Nivel Inicial', 'Profesional'),
    ('Ciencias de la Educación. Nivel Secundaria. Especialidad Lengua y Literatura', 'Profesional'),
    ('Ciencias de la Electrónica con mención en Control y Automatización', 'Profesional'),
    ('Ciencias de la Electrónica con mención en Ingeniería Biomédica', 'Profesional'),
    ('Ciencias de la Electrónica con mención en Telecomunicaciones', 'Profesional'),
    ('Ciencias de la Gestión Económico Empresarial', 'Profesional'),
    ('Ciencias de la Información', 'Profesional'),
    ('Ciencias de la Nutrición', 'Profesional'),
    ('Ciencias de la Salud', 'Profesional'),
    ('Ciencias de la Salud con mención en Educación para la Salud', 'Profesional'),
    ('Ciencias del Deporte', 'Profesional'),
    ('Ciencias e Ingeniería Biológicas', 'Profesional'),
    ('Ciencias Económicas y Sociales, Mención: Economía y Sociología', 'Profesional'),
    ('Ciencias Estomatológicas', 'Profesional'),
    ('Ciencias Farmacéuticas y Bioquímica', 'Profesional'),
    ('Ciencias Fiscalizadoras con mención en Auditoría Gubernamental', 'Profesional'),
    ('Ciencias Fiscalizadoras con mención en Auditoría Integral Empresarial', 'Profesional'),
    ('Ciencias Físico Matemáticas: Física', 'Profesional'),
    ('Ciencias Físico Matemáticas: Matemáticas', 'Profesional'),
    ('Ciencias Forestales y del Ambiente', 'Profesional'),
    ('Ciencias Gastronómicas', 'Profesional'),
    ('Ciencias Histórico Sociales', 'Profesional'),
    ('Ciencias Histórico Sociales y Geográficas', 'Profesional'),
    ('Ciencias Marítimas', 'Profesional'),
    ('Ciencias Marítimas Navales', 'Profesional'),
    ('Ciencias Marítimas Navales con Mención en Administración', 'Profesional'),
    ('Ciencias Marítimas Navales con Mención en Comando General', 'Profesional'),
    ('Ciencias Marítimas Navales con Mención en Guardacostas', 'Profesional'),
    ('Ciencias Médicas', 'Profesional'),
    ('Ciencias Militares', 'Profesional'),
    ('Ciencias Militares con Especialidad en Artillería', 'Profesional'),
    ('Ciencias Militares con Especialidad en Caballería', 'Profesional'),
    ('Ciencias Militares con Especialidad en Comunicaciones', 'Profesional'),
    ('Ciencias Militares con Especialidad en Infantería', 'Profesional'),
    ('Ciencias Militares con Especialidad en Ingeniería', 'Profesional'),
    ('Ciencias Militares con Especialidad en Inteligencia e Intendencia con la Mención en Administración', 'Profesional'),
    ('Ciencias Militares con Especialidad en Material de Guerra con la Mención en Ingeniería', 'Profesional'),
    ('Ciencias Militares con Mención en Planeamiento Administrativo y Toma de Decisiones', 'Profesional'),
    ('Ciencias Militares con Mención en Planeamiento Operacional y Toma de Decisiones', 'Profesional'),
    ('Ciencias para el Desarrollo Sustentable', 'Profesional'),
    ('Ciencias Penales', 'Profesional'),
    ('Ciencias Políticas', 'Profesional'),
    ('Ciencias Políticas y Relaciones Internacionales', 'Profesional'),
    ('Ciencias Químicas', 'Profesional'),
    ('Ciencias Sociales', 'Profesional'),
    ('Ciencias Sociales y Desarrollo Rural', 'Profesional'),
    ('Ciencias Teológicas y Educación Religiosa', 'Profesional'),
    ('Ciencias Veterinarias', 'Profesional'),
    ('Ciencias y Tecnologías de la Comunicación', 'Profesional'),
    ('Cinematografía', 'Profesional'),
    ('Cirugía', 'Profesional'),
    ('Cirugía Bucal y Maxilofacial', 'Profesional'),
    ('Cirugía Buco Máxilo Facial', 'Profesional'),
    ('Cirugía de Cabeza y Cuello', 'Profesional'),
    ('Cirugía de Cabeza, Cuello y Maxilofacial', 'Profesional'),
    ('Cirugía de Colon, Recto y Ano', 'Profesional'),
    ('Cirugía de Mano', 'Profesional'),
    ('Cirugía de Retina y Vítreo', 'Profesional'),
    ('Cirugía de Tórax Oncológica', 'Profesional'),
    ('Cirugía de Tórax y Cardiovascular', 'Profesional'),
    ('Cirugía General', 'Profesional'),
    ('Cirugía Hepatopancreatobiliar y Transplante', 'Profesional'),
    ('Cirugía Oncológica', 'Profesional'),
    ('Cirugía Oncológica Abdominal', 'Profesional'),
    ('Cirugía Oncológica de Cabeza y Cuello', 'Profesional'),
    ('Cirugía Oncológica de Mama, Tejidos Blandos y Piel', 'Profesional'),
    ('Cirugía Oncológica de Mamas, Tejidos Blandos y Piel', 'Profesional'),
    ('Cirugía Pediátrica', 'Profesional'),
    ('Cirugía Plástica', 'Profesional'),
    ('Cirugía Plástica y Reconstructiva', 'Profesional'),
    ('Citología', 'Profesional'),
    ('Clínica de Animales Menores', 'Profesional'),
    ('Clínica Quirúrgica de Pequeños Animales', 'Profesional'),
    ('Clínica y Patología Aviar', 'Profesional'),
    ('Cognición, Aprendizaje y Desarrollo', 'Profesional'),
    ('Comercio Internacional y Aduanas', 'Profesional'),
    ('Comercio y Negociaciones Internacionales', 'Profesional'),
    ('Comercio y Negocios Internacionales', 'Profesional'),
    ('Complementación Académica (Bachillerato)', 'Profesional'),
    ('Complementación Pedagógica', 'Profesional'),
    ('Complementación Universitaria', 'Profesional'),
    ('Complementación Universitaria en Archivística y Gestión Documental', 'Profesional'),
    ('Composición con Especialidad de Composición', 'Profesional'),
    ('Computación Científica', 'Profesional'),
    ('Computación e Informática', 'Profesional'),
    ('Comunicación', 'Profesional'),
    ('Comunicación Audiovisual', 'Profesional'),
    ('Comunicación Audiovisual en Medios Digitales', 'Profesional'),
    ('Comunicación Audiovisual y Cine', 'Profesional'),
    ('Comunicación Audiovisual y Medios Interactivos', 'Profesional'),
    ('Comunicación Corporativa', 'Profesional'),
    ('Comunicación e Imagen Corporativa', 'Profesional'),
    ('Comunicación e Imagen Empresarial', 'Profesional'),
    ('Comunicación Empresarial y Marketing Digital', 'Profesional'),
    ('Comunicación en Medios Digitales', 'Profesional'),
    ('Comunicación en Salud', 'Profesional'),
    ('Comunicación Estratégica y Publicidad Digital', 'Profesional'),
    ('Comunicación Integral', 'Profesional'),
    ('Comunicación Organizacional', 'Profesional'),
    ('Comunicación para el Desarrollo', 'Profesional'),
    ('Comunicación Social', 'Profesional'),
    ('Comunicación y Diseño Gráfico', 'Profesional'),
    ('Comunicación y Fotografía', 'Profesional'),
    ('Comunicación y Marketing', 'Profesional'),
    ('Comunicación y Marketing Digital', 'Profesional'),
    ('Comunicación y Medios Digitales', 'Profesional'),
    ('Comunicación y Periodismo', 'Profesional'),
    ('Comunicación y Publicidad', 'Profesional'),
    ('Comunicación y Publicidad Transmedia', 'Profesional'),
    ('Comunicación, Matemática y Ciencia - Nivel de Educación Primaria', 'Profesional'),
    ('Comunicaciones', 'Profesional'),
    ('Comunicaciones de Marketing', 'Profesional'),
    ('Conservación de Recursos Forestales', 'Profesional'),
    ('Conservación y Restauración', 'Profesional'),
    ('Conservación y Restauración de Monumentos Históricos y Artísticos', 'Profesional'),
    ('Conservación y Restauración de Obras de Arte', 'Profesional'),
    ('Contabilidad', 'Profesional'),
    ('Contabilidad con Mención en Finanzas', 'Profesional'),
    ('Contabilidad Empresarial', 'Profesional'),
    ('Contabilidad Financiera', 'Profesional'),
    ('Contabilidad Gerencial', 'Profesional'),
    ('Contabilidad y Administración', 'Profesional'),
    ('Contabilidad y Auditoría', 'Profesional'),
    ('Contabilidad y Finanzas', 'Profesional'),
    ('Contabilidad y Finanzas (Virtual: Semipresencial)', 'Profesional'),
    ('Contabilidad, Gestión Tributaria y Aduanera', 'Profesional'),
    ('Contabilidad, mención: Auditoría', 'Profesional'),
    ('Corporate Master Of Business Administration (CMBA)', 'Profesional'),
    ('Creación y Producción Escénica', 'Profesional'),
    ('Crecimiento y Desarrollo', 'Profesional'),
    ('Criminalística Financiera Forense', 'Profesional'),
    ('Criminología', 'Profesional'),
    ('Cuidado Enfermero en Crecimiento y Desarrollo', 'Profesional'),
    ('Cuidado Enfermero en Emergencias y Desastres', 'Profesional'),
    ('Cuidado Enfermero en Estimulación Temprana', 'Profesional'),
    ('Cuidado Enfermero en Gastroenterología con Mención en Endoscopia y Procedimientos Especiales', 'Profesional'),
    ('Cuidado Enfermero en Neonatología', 'Profesional'),
    ('Cuidado Enfermero en Paciente Crítico', 'Profesional'),
    ('Cuidado Enfermero en Paciente Crítico con Mención en Adulto', 'Profesional'),
    ('Cuidados Intensivos', 'Profesional'),
    ('Cuidados Intensivos - Adulto', 'Profesional'),
    ('Cuidados Intensivos - Neonatología', 'Profesional'),
    ('Danza', 'Profesional'),
    ('Defensa Nacional', 'Profesional'),
    ('Derecho', 'Profesional'),
    ('Derecho (Horario diferenciado)', 'Profesional'),
    ('Derecho Administrativo', 'Profesional'),
    ('Derecho Bancario y Financiero', 'Profesional'),
    ('Derecho Bancario y Financiero con Mención en Gestión Financiera', 'Profesional'),
    ('Derecho Bancario y Financiero con Mención en Regulación Bancaria', 'Profesional'),
    ('Derecho Civil', 'Profesional'),
    ('Derecho Civil y Comercial', 'Profesional'),
    ('Derecho con Mención en Política Jurisdiccional', 'Profesional'),
    ('Derecho con Mención en Política Jurisdiccional Especialidad en Gestión y Política Judicial', 'Profesional'),
    ('Derecho Constitucional', 'Profesional'),
    ('Derecho Constitucional y Administrativo', 'Profesional'),
    ('Derecho Corporativo', 'Profesional'),
    ('Derecho de Familia', 'Profesional'),
    ('Derecho de la Empresa', 'Profesional'),
    ('Derecho de la Empresa con Mención en Responsabilidad Social', 'Profesional'),
    ('Derecho de la Empresa: Banca y Finanzas', 'Profesional'),
    ('Derecho de la Empresa: Gestión Empresarial', 'Profesional'),
    ('Derecho de la Empresa: Regulación de Negocios', 'Profesional'),
    ('Derecho de la Propiedad Intelectual y de la Competencia', 'Profesional'),
    ('Derecho de Propiedad Intelectual, Competencia y Regulación', 'Profesional'),
    ('Derecho del Trabajo', 'Profesional'),
    ('Derecho del Trabajo y de la Seguridad Social', 'Profesional'),
    ('Derecho Deportivo', 'Profesional'),
    ('Derecho en Ciencias Penales', 'Profesional'),
    ('Derecho en Ciencias Penales (Virtual: Semipresencial)', 'Profesional'),
    ('Derecho Internacional Económico', 'Profesional'),
    ('Derecho Internacional Marítimo y Portuario', 'Profesional'),
    ('Derecho Laboral y Gestión Legal de Recursos Humanos', 'Profesional'),
    ('Derecho Notarial y Registral', 'Profesional'),
    ('Derecho Penal', 'Profesional'),
    ('Derecho Procesal', 'Profesional'),
    ('Derecho Procesal Constitucional y Administrativo', 'Profesional'),
    ('Derecho Procesal Penal', 'Profesional'),
    ('Derecho Registral y Notarial', 'Profesional'),
    ('Derecho Tributario', 'Profesional'),
    ('Derecho Tributario y Fiscalidad Internacional', 'Profesional'),
    ('Derecho y Ciencia Política', 'Profesional'),
    ('Derecho y Ciencias Políticas', 'Profesional'),
    ('Derecho y Gestión Pública', 'Profesional'),
    ('Derecho, mención en Ciencias Penales', 'Profesional'),
    ('Derechos Humanos', 'Profesional'),
    ('Derechos Humanos con Mención en Pueblos Indígenas', 'Profesional'),
    ('Dermatología', 'Profesional'),
    ('Dermatología Pediátrica', 'Profesional'),
    ('Desarrollo Ambiental', 'Profesional'),
    ('Desarrollo Humano: Enfoques y Políticas', 'Profesional'),
    ('Didáctica de la Enseñanza de la Física y Matemática', 'Profesional'),
    ('Didáctica de la Matemática para la Educación Primaria', 'Profesional'),
    ('Digital Business Management', 'Profesional'),
    ('Diplomacia y Relaciones Internacionales', 'Profesional'),
    ('Dirección de Cadenas de Aprovisionamiento', 'Profesional'),
    ('Dirección de Empresas Industriales y de Servicios', 'Profesional'),
    ('Dirección de la Construcción', 'Profesional'),
    ('Dirección de Marketing', 'Profesional'),
    ('Dirección de Operaciones Productivas', 'Profesional'),
    ('Dirección Estratégica de Las Telecomunicaciones', 'Profesional'),
    ('Dirección Estratégica y Liderazgo', 'Profesional'),
    ('Dirección Financiera y Contable', 'Profesional'),
    ('Dirección y Administración de Empresas (MBA) (Virtual: Semipresencial)', 'Profesional'),
    ('Diseño de Interiores', 'Profesional'),
    ('Diseño Digital de Interiores', 'Profesional'),
    ('Diseño Digital Publicitario', 'Profesional'),
    ('Diseño Estratégico', 'Profesional'),
    ('Diseño Gráfico', 'Profesional'),
    ('Diseño Gráfico Digital', 'Profesional'),
    ('Diseño Gráfico Digital y Publicitario', 'Profesional'),
    ('Diseño Gráfico Profesional', 'Profesional'),
    ('Diseño Gráfico Publicitario', 'Profesional'),
    ('Diseño Gráfico y Marketing Digital', 'Profesional'),
    ('Diseño Industrial', 'Profesional'),
    ('Diseño Interactivo', 'Profesional'),
    ('Diseño Interactivo UX', 'Profesional'),
    ('Diseño Profesional de Interiores', 'Profesional'),
    ('Diseño Profesional Gráfico', 'Profesional'),
    ('Diseño y Construcción de Obras Viales', 'Profesional'),
    ('Diseño y Evaluación Curricular', 'Profesional'),
    ('Diseño y Gestión de Marca', 'Profesional'),
    ('Diseño y Gestión en Moda', 'Profesional'),
    ('Docencia del Idioma Inglés', 'Profesional'),
    ('Docencia e Investigación en Salud', 'Profesional'),
    ('Docencia Superior y Universitaria', 'Profesional'),
    ('Docencia Universitaria', 'Profesional'),
    ('Docencia y Gestión Universitaria', 'Profesional'),
    ('Docente en Danza Clásica', 'Profesional'),
    ('Doctor en Ciencias', 'Profesional'),
    ('Doctorado de Ciencias de Enfermería', 'Profesional'),
    ('Doctorado en Administración', 'Profesional'),
    ('Doctorado en Administración (DBA)', 'Profesional'),
    ('Doctorado en Administración (DBA), con Mención en Gestión de Gobierno y Políticas Públicas', 'Profesional'),
    ('Doctorado en Administración de Empresas', 'Profesional'),
    ('Doctorado en Administración de Negocios', 'Profesional'),
    ('Doctorado en Administración de Negocios Globales', 'Profesional'),
    ('Doctorado en Administración Estratégica de Negocios', 'Profesional'),
    ('Doctorado en Ambiente y Desarrollo Sostenible', 'Profesional'),
    ('Doctorado en Antropología', 'Profesional'),
    ('Doctorado en Arquitectura', 'Profesional'),
    ('Doctorado en Arquitectura y Dinámicas Urbanas', 'Profesional'),
    ('Doctorado en Arquitectura y Urbanismo', 'Profesional'),
    ('Doctorado en Bienestar Social y Desarrollo Local', 'Profesional'),
    ('Doctorado en Biociencias con Mención en Multi-ómicas de la Biodiversidad y Biotecnología Aplicada', 'Profesional'),
    ('Doctorado en Biología', 'Profesional'),
    ('Doctorado en Biología Ambiental', 'Profesional'),
    ('Doctorado en Biomedicina', 'Profesional'),
    ('Doctorado en Biotecnología', 'Profesional'),
    ('Doctorado en Business Administration – DBA', 'Profesional'),
    ('Doctorado en Ciencia Animal', 'Profesional'),
    ('Doctorado en Ciencia Contable', 'Profesional'),
    ('Doctorado en Ciencia e Ingeniería de la Computación', 'Profesional'),
    ('Doctorado en Ciencia Política y Relaciones Internacionales', 'Profesional'),
    ('Doctorado en Ciencia y Tecnología de los Alimentos', 'Profesional'),
    ('Doctorado en Ciencia, Tecnología y Medio Ambiente', 'Profesional'),
    ('Doctorado en Ciencias Administrativas con Mención en Dirección de Empresas', 'Profesional'),
    ('Doctorado en Ciencias Agrarias', 'Profesional'),
    ('Doctorado en Ciencias Agropecuarias', 'Profesional'),
    ('Doctorado en Ciencias Ambientales', 'Profesional'),
    ('Doctorado en Ciencias Ambientales y Desarrollo Sostenible', 'Profesional'),
    ('Doctorado en Ciencias Ambientales y Energías Renovables', 'Profesional'),
    ('Doctorado en Ciencias Biológicas', 'Profesional'),
    ('Doctorado en Ciencias Biomédicas', 'Profesional'),
    ('Doctorado en Ciencias con Mención en Bioquímica y Biología Molecular', 'Profesional'),
    ('Doctorado en Ciencias con Mención en Derecho', 'Profesional'),
    ('Doctorado en Ciencias con Mención en Ecología Amazónica', 'Profesional'),
    ('Doctorado en Ciencias con Mención en Energética', 'Profesional'),
    ('Doctorado en Ciencias con Mención en Física', 'Profesional'),
    ('Doctorado en Ciencias con Mención en Fisiología', 'Profesional'),
    ('Doctorado en Ciencias con Mención en Matemática', 'Profesional'),
    ('Doctorado en Ciencias con Mención en Microbiología', 'Profesional'),
    ('Doctorado en Ciencias con Mención en Química', 'Profesional'),
    ('Doctorado en Ciencias con Mención en Sistemas Electrónicos y Sistemas Inteligentes', 'Profesional'),
    ('Doctorado en Ciencias Contables', 'Profesional'),
    ('Doctorado en Ciencias Contables y Financieras', 'Profesional'),
    ('Doctorado en Ciencias de Enfermería', 'Profesional'),
    ('Doctorado en Ciencias de la Administración', 'Profesional'),
    ('Doctorado en Ciencias de la Computación', 'Profesional'),
    ('Doctorado en Ciencias de la Comunicación', 'Profesional'),
    ('Doctorado en Ciencias de la Educación', 'Profesional'),
    ('Doctorado en Ciencias de la Ingeniería Mecánica Eléctrica', 'Profesional'),
    ('Doctorado en Ciencias de la Ingeniería Mecánica y Eléctrica con mención en Energía', 'Profesional'),
    ('Doctorado en Ciencias de la Ingeniería y Tecnología', 'Profesional'),
    ('Doctorado en Ciencias de la Salud', 'Profesional'),
    ('Doctorado en Ciencias de la Salud y Salud Pública', 'Profesional'),
    ('Doctorado en Ciencias De La Vida', 'Profesional'),
    ('Doctorado en Ciencias del Desarrollo Social', 'Profesional'),
    ('Doctorado en Ciencias e Ingeniería', 'Profesional'),
    ('Doctorado en Ciencias e Ingeniería Ambientales con mención en Abastecimiento de Agua y Saneamiento', 'Profesional'),
    ('Doctorado en Ciencias e Ingeniería Ambientales con mención en Desarrollo Sostenible', 'Profesional'),
    ('Doctorado en Ciencias e Ingeniería Ambientales con mención en Seguridad Industrial y Salud en el Trabajo', 'Profesional'),
    ('Doctorado en Ciencias e Ingeniería Civil', 'Profesional'),
    ('Doctorado en Ciencias e Ingeniería Económica', 'Profesional'),
    ('Doctorado en Ciencias e Ingeniería Estadística', 'Profesional'),
    ('Doctorado en Ciencias Económicas', 'Profesional'),
    ('Doctorado en Ciencias Económicas y Financieras', 'Profesional'),
    ('Doctorado en Ciencias Empresariales', 'Profesional'),
    ('Doctorado en Ciencias en Arquitectura', 'Profesional'),
    ('Doctorado en Ciencias en Enfermería', 'Profesional'),
    ('Doctorado en Ciencias en Investigación Epidemiológica', 'Profesional'),
    ('Doctorado en Ciencias en Salud Pública', 'Profesional'),
    ('Doctorado en Ciencias Forestales, con mención en Bosques y Cambio Climático', 'Profesional'),
    ('Doctorado en Ciencias Gobernabilidad y Gestión Pública Estratégica', 'Profesional'),
    ('Doctorado en Ciencias Matemáticas', 'Profesional'),
    ('Doctorado en Ciencias Materiales', 'Profesional'),
    ('Doctorado en Ciencias Químicas', 'Profesional'),
    ('Doctorado en Ciencias Sociales', 'Profesional'),
    ('Doctorado en Ciencias Sociales, Gestión Pública y Desarrollo Territorial', 'Profesional'),
    ('Doctorado en Ciencias y Tecnologías Medioambientales', 'Profesional'),
    ('Doctorado en Ciencias, Tecnologías Acuícolas y Pesqueras', 'Profesional'),
    ('Doctorado en Ciencias: Educación', 'Profesional'),
    ('Doctorado en Ciencias: Enfermería', 'Profesional'),
    ('Doctorado en Ciencias: Ingeniería Mecatrónica', 'Profesional'),
    ('Doctorado en Ciencias: Protección Vegetal', 'Profesional'),
    ('Doctorado en Ciencias: Química', 'Profesional'),
    ('Doctorado en Ciencias: Salud Colectiva', 'Profesional'),
    ('Doctorado en Ciencias: Salud Pública', 'Profesional'),
    ('Doctorado en Comunicación', 'Profesional'),
    ('Doctorado en Comunicación Social', 'Profesional'),
    ('Doctorado en Comunicación y Desarrollo', 'Profesional'),
    ('Doctorado en Comunicación, Periodismo y Medios Digitales', 'Profesional'),
    ('Doctorado en Contabilidad', 'Profesional'),
    ('Doctorado en Contabilidad y Finanzas', 'Profesional'),
    ('Doctorado en Deep Tech con enfoque en Inteligencia Artificial y Tecnologías Emergentes', 'Profesional'),
    ('Doctorado en Derecho', 'Profesional'),
    ('Doctorado en Derecho e Investigación Jurídíca', 'Profesional'),
    ('Doctorado en Derecho Penal y Política Criminal', 'Profesional'),
    ('Doctorado en Derecho y Ciencia Política', 'Profesional'),
    ('Doctorado en Derecho y Ciencias Políticas', 'Profesional'),
    ('Doctorado en Desarrollo Organizacional y Gestión del Talento', 'Profesional'),
    ('Doctorado en Desarrollo y Seguridad Estratégica', 'Profesional'),
    ('Doctorado en Didáctica de Las Ciencias', 'Profesional'),
    ('Doctorado en Dirección de Empresas', 'Profesional'),
    ('Doctorado en Dirección Estratégica con mención en Gestión de la Seguridad y Defensa', 'Profesional'),
    ('Doctorado en Economía', 'Profesional'),
    ('Doctorado en Economía de los Recursos Naturales', 'Profesional'),
    ('Doctorado en Economía y Desarrollo Industrial', 'Profesional'),
    ('Doctorado en Economía y Negocios Internacionales', 'Profesional'),
    ('Doctorado en Economía y Políticas Públicas', 'Profesional'),
    ('Doctorado en Educación', 'Profesional'),
    ('Doctorado en Educación Ambiental', 'Profesional'),
    ('Doctorado en Educación con mención en Currículo y Docencia', 'Profesional'),
    ('Doctorado en Educación con Mención en Gestión Educativa', 'Profesional'),
    ('Doctorado en Educación Intercultural', 'Profesional'),
    ('Doctorado en Educación y Docencia Universitaria', 'Profesional'),
    ('Doctorado en Enfermería', 'Profesional'),
    ('Doctorado en Epidemiología', 'Profesional'),
    ('Doctorado en Estadística', 'Profesional'),
    ('Doctorado en Estadística Aplicada', 'Profesional'),
    ('Doctorado en Estadística e Informática', 'Profesional'),
    ('Doctorado en Estadística Matemática', 'Profesional'),
    ('Doctorado en Estadística Matemática Aplicada', 'Profesional'),
    ('Doctorado en Estado, Política y Gestión Pública', 'Profesional'),
    ('Doctorado en Estomatología', 'Profesional'),
    ('Doctorado en Estudios Sociales y Humanísticos', 'Profesional'),
    ('Doctorado en Farmacia y Bioquímica', 'Profesional'),
    ('Doctorado en Filosofía, Mención Educación', 'Profesional'),
    ('Doctorado en Física', 'Profesional'),
    ('Doctorado en Genética y Desarrollo Humano', 'Profesional'),
    ('Doctorado en Gerencia de Empresas', 'Profesional'),
    ('Doctorado en Gestión de Recursos Humanos y Desarrollo Organizacional', 'Profesional'),
    ('Doctorado en Gestión Empresarial', 'Profesional'),
    ('Doctorado en Gestión Estratégica', 'Profesional'),
    ('Doctorado en Gestión Estratégica y Transformación Digital', 'Profesional'),
    ('Doctorado en Gestión Pública', 'Profesional'),
    ('Doctorado en Gestión Pública y Gobernabilidad', 'Profesional'),
    ('Doctorado en Gestión Universitaria', 'Profesional'),
    ('Doctorado en Gestión y Políticas Públicas', 'Profesional'),
    ('Doctorado en Gobierno de Organizaciones', 'Profesional'),
    ('Doctorado en Gobierno y Administración Pública', 'Profesional'),
    ('Doctorado en Gobierno y Políticas Públicas', 'Profesional'),
    ('Doctorado en Hidrógeno Verde', 'Profesional'),
    ('Doctorado en Humanidades', 'Profesional'),
    ('Doctorado en Humanidades con Mención en Estudios Sobre Cultura', 'Profesional'),
    ('Doctorado en Ingeniería', 'Profesional'),
    ('Doctorado en Ingeniería Agroindustrial', 'Profesional'),
    ('Doctorado en Ingeniería Agroindustrial con mención en Transformación Avanzada de Granos y Tubérculos Andinos', 'Profesional'),
    ('Doctorado en Ingeniería Ambiental', 'Profesional'),
    ('Doctorado en Ingeniería Bioquímica', 'Profesional'),
    ('Doctorado en Ingeniería Civil', 'Profesional'),
    ('Doctorado en Ingeniería de Alimentos', 'Profesional'),
    ('Doctorado en Ingeniería de Procesos', 'Profesional'),
    ('Doctorado en Ingeniería de Sistemas', 'Profesional'),
    ('Doctorado en Ingeniería de Sistemas e Informática', 'Profesional'),
    ('Doctorado en Ingeniería en Energía', 'Profesional'),
    ('Doctorado en Ingeniería Industrial', 'Profesional'),
    ('Doctorado en Ingeniería Mecánica', 'Profesional'),
    ('Doctorado en Ingeniería Química', 'Profesional'),
    ('Doctorado en Ingeniería Química Ambiental', 'Profesional'),
    ('Doctorado en Ingeniería Química y Ambiental', 'Profesional'),
    ('Doctorado en Ingeniería y Ciencias Aplicadas', 'Profesional'),
    ('Doctorado en Ingeniería, Mención Automatización, Control y Optimización de Procesos', 'Profesional'),
    ('Doctorado en Investigación Clínica y Traslacional', 'Profesional'),
    ('Doctorado en Matemática', 'Profesional'),
    ('Doctorado en Matemática Aplicada', 'Profesional'),
    ('Doctorado en Medicina', 'Profesional'),
    ('Doctorado en Medio Ambiente y Desarrollo Sostenible', 'Profesional'),
    ('Doctorado en Medio Ambiente y Desarrollo Sustentable', 'Profesional'),
    ('Doctorado en Microbiología', 'Profesional'),
    ('Doctorado en Neurociencias', 'Profesional'),
    ('Doctorado en Nutrición', 'Profesional'),
    ('Doctorado en Nutrición y Alimentación', 'Profesional'),
    ('Doctorado en Obstetricia', 'Profesional'),
    ('Doctorado en Odontología', 'Profesional'),
    ('Doctorado en Planificación Pública y Privada', 'Profesional'),
    ('Doctorado en Planificación y Gestión', 'Profesional'),
    ('Doctorado en Políticas Públicas y Gestión del Estado', 'Profesional'),
    ('Doctorado en Políticas Publicas y Gestión Integrada del Riesgo de Desastres', 'Profesional'),
    ('Doctorado en Producción Vegetal y Ecosistemas Agroforestales', 'Profesional'),
    ('Doctorado en Psicología', 'Profesional'),
    ('Doctorado en Psicología Educacional y Tutorial', 'Profesional'),
    ('Doctorado en Recursos Hídricos', 'Profesional'),
    ('Doctorado en Recursos Naturales y Desarrollo Sustentable', 'Profesional'),
    ('Doctorado en Sagrada Teología', 'Profesional'),
    ('Doctorado en salud global con mención en ciencias de la implementación', 'Profesional'),
    ('Doctorado en Salud Pública', 'Profesional'),
    ('Doctorado en Salud Pública e Investigación', 'Profesional'),
    ('Doctorado en Salud Pública y Salud Global', 'Profesional'),
    ('Doctorado en Seguridad y Control en Minería', 'Profesional'),
    ('Doctorado en Seguridad y Medio Ambiente', 'Profesional'),
    ('Doctorado en Sociología', 'Profesional'),
    ('Doctorado en Tecnologías de la Información y Comunicaciones', 'Profesional'),
    ('Doctorado en Teología', 'Profesional'),
    ('Doctorado en Territorio y Urbanismo Sostenible', 'Profesional'),
    ('E-Business', 'Profesional'),
    ('E-Business (Virtual: Semipresencial)', 'Profesional'),
    ('Ecografía Obstétrica y Monitoreo Electrónico Materno Fetal', 'Profesional'),
    ('Ecología Aplicada', 'Profesional'),
    ('Economía', 'Profesional'),
    ('Economía (Virtual: Semipresencial)', 'Profesional'),
    ('Economía Agraria', 'Profesional'),
    ('Economía Agrícola', 'Profesional'),
    ('Economía con Mención en Banca y Finanzas', 'Profesional'),
    ('Economía con Mención en Comercio y Finanzas Internacionales', 'Profesional'),
    ('Economía con Mención en Economía Aplicada', 'Profesional'),
    ('Economía con Mención en Economía Empresarial', 'Profesional'),
    ('Economía de Los Recursos Naturales y del Ambiente', 'Profesional'),
    ('Economía de Los Recursos Naturales y el Desarrollo Sustentable', 'Profesional'),
    ('Economía Financiera', 'Profesional'),
    ('Economía Gerencial', 'Profesional'),
    ('Economía Internacional', 'Profesional'),
    ('Economía Pública', 'Profesional'),
    ('Economía y Ciencia de Datos', 'Profesional'),
    ('Economía y Desarrollo', 'Profesional'),
    ('Economía y Finanzas', 'Profesional'),
    ('Economía y Gestión Ambiental', 'Profesional'),
    ('Economía y Negocios Internacionales', 'Profesional'),
    ('Economía y Políticas Públicas', 'Profesional'),
    ('Economía y Relaciones Internacionales', 'Profesional'),
    ('Ecoturismo', 'Profesional'),
    ('Edificaciones Inteligentes y Dirección de la Construcción', 'Profesional'),
    ('Educación', 'Profesional'),
    ('Educación Artística', 'Profesional'),
    ('Educación Artística – Especialidad: Danzas Folklóricas', 'Profesional'),
    ('Educación Artística – Especialidad: Teatro', 'Profesional'),
    ('Educación Artística Artes Plásticas Visuales', 'Profesional'),
    ('Educación Artística con Especialidad de Música', 'Profesional'),
    ('Educación Artística con Especialidad en Arte Dramático', 'Profesional'),
    ('Educación Artística con Especialidad en Artes Plásticas', 'Profesional'),
    ('Educación Artística con Especialidad en Artes Plásticas y Visuales', 'Profesional'),
    ('Educación Artística con Especialidad en Artes Visuales', 'Profesional'),
    ('Educación Artística con Especialidad en Danza', 'Profesional'),
    ('Educación Artística con Especialidad en Música', 'Profesional'),
    ('Educación Artística con Especialidad en Teatro', 'Profesional'),
    ('Educación Artística con la especialidad de Artes Plásticas', 'Profesional'),
    ('Educación Artística con la especialidad de Danza', 'Profesional'),
    ('Educación Artística con la especialidad de Música', 'Profesional'),
    ('Educación Artística con Mención en Artes Plásticas', 'Profesional'),
    ('Educación Artística con Mención en Danza', 'Profesional'),
    ('Educación Artística con Mención en Música', 'Profesional'),
    ('Educación Artística con Mención en Teatro', 'Profesional'),
    ('Educación Artística Especialidad de Artes Plásticas', 'Profesional'),
    ('Educación Artística Especialidad de Música', 'Profesional'),
    ('Educación Artística Especialidad Música', 'Profesional'),
    ('Educación Artística y Promotoria Cultural', 'Profesional'),
    ('Educación Artística, Especialidad: Artes Plásticas y Visuales', 'Profesional'),
    ('Educación Artística, Especialidad: Danza', 'Profesional'),
    ('Educación Artística, Especialidad: Educación Musical', 'Profesional'),
    ('Educación Artística: Especialidad de Artes Plásticas', 'Profesional'),
    ('Educación Artística: Especialidad de Danza Folklórica', 'Profesional'),
    ('Educación Artística: Especialidad de Música', 'Profesional'),
    ('Educación Básica Alternativa', 'Profesional'),
    ('Educación Básica: Inicial y Primaria', 'Profesional'),
    ('Educación con especialidad de Agropecuaria', 'Profesional'),
    ('Educación con especialidad de Artes Industriales', 'Profesional'),
    ('Educación con especialidad de Automatización Industrial', 'Profesional'),
    ('Educación con especialidad de Biología-Ciencias Naturales', 'Profesional'),
    ('Educación con especialidad de Biología-Informática', 'Profesional'),
    ('Educación con Especialidad de Ciencias Naturales', 'Profesional'),
    ('Educación con Especialidad de Ciencias Sociales', 'Profesional'),
    ('Educación con especialidad de Ciencias Sociales-Filosofía', 'Profesional'),
    ('Educación con especialidad de Ciencias Sociales-Geografía', 'Profesional'),
    ('Educación con especialidad de Ciencias Sociales-Historia', 'Profesional'),
    ('Educación con especialidad de Ciencias Sociales-Psicología', 'Profesional'),
    ('Educación con especialidad de Construcción Civil', 'Profesional'),
    ('Educación con especialidad de Construcciones Metálicas', 'Profesional'),
    ('Educación con especialidad de Desarrollo Ambiental', 'Profesional'),
    ('Educación con especialidad de Diseño Industrial y Arquitectónico', 'Profesional'),
    ('Educación con especialidad de Ebanistería y Decoración', 'Profesional'),
    ('Educación con especialidad de Educación Artística-Artes Plásticas', 'Profesional'),
    ('Educación con Especialidad de Educación Artística-Música', 'Profesional'),
    ('Educación con especialidad de Educación Artística-Teatro', 'Profesional'),
    ('Educación con Especialidad de Educación Básica Alternativa-Educación Primaria', 'Profesional'),
    ('Educación con Especialidad de Educación Física', 'Profesional'),
    ('Educación con especialidad de Educación Física-Deportes', 'Profesional'),
    ('Educación con especialidad de Educación Física-Edades Tempranas', 'Profesional'),
    ('Educación con Especialidad de Educación Física-Poblaciones Especiales', 'Profesional'),
    ('Educación con Especialidad de Educación Física-Recreación y Deporte Para Todos', 'Profesional'),
    ('Educación con Especialidad de Educación Inicial', 'Profesional'),
    ('Educación con especialidad de Educación Inicial-Discapacidad Intelectual', 'Profesional'),
    ('Educación con especialidad de Educación Inicial-Niñez Temprana', 'Profesional'),
    ('Educación con especialidad de Educación Intercultural Bilingüe-Lengua Española', 'Profesional'),
    ('Educación con Especialidad de Educación Primaria', 'Profesional'),
    ('Educación con Especialidad de Educación Primaria-Educación Básica Alternativa', 'Profesional'),
    ('Educación con especialidad de Electricidad', 'Profesional'),
    ('Educación con especialidad de Electrónica e Informática', 'Profesional'),
    ('Educación con especialidad de Física-Matemática', 'Profesional'),
    ('Educación con Especialidad de Físico Matemática', 'Profesional'),
    ('Educación con especialidad de Fuerza Motriz', 'Profesional'),
    ('Educación con Especialidad de Idiomas (Inglés-Francés)', 'Profesional'),
    ('Educación con especialidad de Industria Alimentaria y Nutrición', 'Profesional'),
    ('Educación con Especialidad de Informática', 'Profesional'),
    ('Educación con Especialidad de Informática Educativa', 'Profesional'),
    ('Educación con especialidad de Inglés-Alemán', 'Profesional'),
    ('Educación con especialidad de Inglés-Español como Lengua Extranjera', 'Profesional'),
    ('Educación con especialidad de Inglés-Francés', 'Profesional'),
    ('Educación con especialidad de Inglés-Italiano', 'Profesional'),
    ('Educación con Especialidad de Lengua Española', 'Profesional'),
    ('Educación con especialidad de Lengua Española-Inglés', 'Profesional'),
    ('Educación con Especialidad de Lengua, Literatura, Filosofía y Psicología', 'Profesional'),
    ('Educación con Especialidad de Literatura', 'Profesional'),
    ('Educación con especialidad de Matemática', 'Profesional'),
    ('Educación con especialidad de Matemática e Informática', 'Profesional'),
    ('Educación con especialidad de Mecánica de Producción', 'Profesional'),
    ('Educación con especialidad de Metalurgia-Joyería', 'Profesional'),
    ('Educación con especialidad de Química, Física y Biología', 'Profesional'),
    ('Educación con especialidad de Química-Ciencias Naturales', 'Profesional'),
    ('Educación con especialidad de Tecnología del Vestido', 'Profesional'),
    ('Educación con especialidad de Tecnología Textil', 'Profesional'),
    ('Educación con especialidad de Telecomunicaciones e Informática', 'Profesional'),
    ('Educación con Especialidad en Ciencia y Tecnología', 'Profesional'),
    ('Educación con Especialidad en Innovación y Aprendizaje Digital', 'Profesional'),
    ('Educación con Especialidad en Letras y Humanidades', 'Profesional'),
    ('Educación con la Especialidad de Educación Especial', 'Profesional'),
    ('Educación con la Especialidad Educación Física', 'Profesional'),
    ('Educación con Mención en Autoevaluación, Acreditación y Certificación', 'Profesional'),
    ('Educación con mención en Ciencias Naturales y Tecnología', 'Profesional'),
    ('Educación con mención en Ciencias Sociales y Comunicación', 'Profesional'),
    ('Educación con Mención en Ciencias Sociales y Comunicación (Virtual: Semipresencial)', 'Profesional'),
    ('Educación con mención en Ciencias Sociales, Filosofía y Religión', 'Profesional'),
    ('Educación con mención en Comunicación, Literatura y Lingüística', 'Profesional'),
    ('Educación con Mención en Currículo', 'Profesional'),
    ('Educación con Mención en Curriculum y Supervisión', 'Profesional'),
    ('Educación con Mención en Desarrollo de Habilidades Cognitivas en la Educación Inicial', 'Profesional'),
    ('Educación con Mención en Desarrollo de Habilidades Comunicativas en la Educación Primaria', 'Profesional'),
    ('Educación con Mención en Desarrollo de Habilidades Comunicativas en la Educación Secundaria', 'Profesional'),
    ('Educación con Mención en Desarrollo del Habla, Audición y Lenguaje', 'Profesional'),
    ('Educación con Mención en Desarrollo del Pensamiento Lógico Matemático en la Educación Primaria', 'Profesional'),
    ('Educación con Mención en Desarrollo del Pensamiento Lógico Matemático en la Educación Secundaria', 'Profesional'),
    ('Educación con Mención en Didáctica de la Comunicación en Educación Secundaria', 'Profesional'),
    ('Educación con Mención en Didáctica de la Educación Ciudadana en Educación Secundaria', 'Profesional'),
    ('Educación con Mención en Didáctica de la Educación Inicial', 'Profesional'),
    ('Educación con Mención en Didáctica de la Educación Primaria', 'Profesional'),
    ('Educación con Mención en Didáctica de la Matemática en Educación Secundaria', 'Profesional'),
    ('Educación con Mención en Dificultades de Aprendizaje', 'Profesional'),
    ('Educación con Mención en Docencia e Investigación Universitaria', 'Profesional'),
    ('Educación con mención en Docencia Virtual', 'Profesional'),
    ('Educación con Mención en Docencia Virtual (Virtual: Semipresencial)', 'Profesional'),
    ('Educación con Mención en Educación Especial', 'Profesional'),
    ('Educación con Mención en Educación Inicial', 'Profesional'),
    ('Educación con Mención en Educación Por el Arte', 'Profesional'),
    ('Educación con mención en Educación Religiosa', 'Profesional'),
    ('Educación con mención en E-Learning', 'Profesional'),
    ('Educación con Mención en E-Learning (Virtual: Semipresencial)', 'Profesional'),
    ('Educación con Mención en Enseñanza de Comunicación y Matemática para Profesores de II y III Ciclo de Educación Básica Regular', 'Profesional'),
    ('Educación con Mención en Enseñanza del Francés', 'Profesional'),
    ('Educación con Mención en Gestión de la Calidad, Autoevaluación y Acreditación', 'Profesional'),
    ('Educación con Mención en Gestión de la Educación', 'Profesional'),
    ('Educación con Mención en Gestión Educativa', 'Profesional'),
    ('Educación con Mención en Gestión Universitaria', 'Profesional'),
    ('Educación con Mención en Gimnasia', 'Profesional'),
    ('Educación con Mención en Informática y Tecnología Educativa', 'Profesional'),
    ('Educación con Mención en Informática y Tecnología Educativa (Virtual: Semipresencial)', 'Profesional'),
    ('Educación con Mención en Inicial', 'Profesional'),
    ('Educación con Mención en Inicial (Virtual: Semipresencial)', 'Profesional'),
    ('Educación con Mención en Investigación Educacional', 'Profesional'),
    ('Educación con Mención en ldiomas Extranjeros', 'Profesional'),
    ('Educación con mención en Matemática e Informática', 'Profesional'),
    ('Educación con Mención en Matemática e Informática (Virtual: Semipresencial)', 'Profesional'),
    ('Educación con mención en Matemáticas e Informática', 'Profesional'),
    ('Educación con Mención en Pedagogía de la Matemática', 'Profesional'),
    ('Educación con Mención en Planificación Educativa', 'Profesional'),
    ('Educación con Mención en Políticas y Gestión de la Educación', 'Profesional'),
    ('Educación con Mención en Políticas y Gestión de la Educación (Virtual: Semipresencial)', 'Profesional'),
    ('Educación con Mención en Primaria', 'Profesional'),
    ('Educación con Mención en Primaria (Virtual: Semipresencial)', 'Profesional'),
    ('Educación con Mención en Problemas de Aprendizaje', 'Profesional'),
    ('Educación con Mención en Retardo Mental', 'Profesional'),
    ('Educación con Mención en Tecnología Educativa', 'Profesional'),
    ('Educación en Idiomas - Inglés', 'Profesional'),
    ('Educación Especial', 'Profesional'),
    ('Educación Especial con Mención en Audición, Lenguaje y Aprendizaje', 'Profesional'),
    ('Educación Especial con mención en Discapacidad Intelectual y Multidiscapacidad', 'Profesional'),
    ('Educación Especialidad de Ciencias Histórico Sociales y Filosofía', 'Profesional'),
    ('Educación Especialidad de Ciencias Naturales', 'Profesional'),
    ('Educación especialidad de Educación Física', 'Profesional'),
    ('Educación Especialidad de Educación Inicial', 'Profesional'),
    ('Educación Especialidad de Educación Primaria', 'Profesional'),
    ('Educación Especialidad de Idiomas Extranjeros', 'Profesional'),
    ('Educación Especialidad de Lengua y Literatura', 'Profesional'),
    ('Educación Especialidad de Matemática y Computación', 'Profesional'),
    ('Educación Especialidad Inicial y Primaria', 'Profesional'),
    ('Carreras de Ingenieria', 'Técnico'),
    ('Carreras Administrativas y de Ciencias Contables', 'Técnico'),
    ('No requiere titulo', 'Secundaria')
  ) AS seed(nombre_carrera, tipo_carrera)
  WHERE NOT EXISTS (SELECT 1 FROM carreras_profesionales);
`;
