/**
 * Catálogo canónico de eventos del Workflow SGC.
 * Compartido BE/FE. Sin dependencias de BD.
 *
 * Reglas:
 * - REQUERIMIENTO_REGISTRADO: creación, destino REGISTRO, NO deriva a Evaluación.
 * - REQUERIMIENTO_ENVIADO_EVALUACION: REGISTRO → EVALUACION.
 * - ORDEN_NOTIFICADA: permanece en REGISTRO_ORDEN.
 * - ORDEN_DERIVADA_EJECUCION: BIEN → RECEPCION_BIENES; SERVICIO/LOCACION → PRESENTACION_ENTREGABLES.
 * - ENTREGA_RECIBIDA / ENTREGABLE_RECIBIDO: eventos internos, no cambian ubicación.
 * - COTIZACIONES_INVALIDAS_DEVUELTAS: VALIDACIONES → INVITACIONES (todas NO_APTO).
 * - LOCACION_APROBADA_RECEPCION: evento interno de LOCACION, RECEPCION_COTIZACIONES → CCP.
 * - VIATICO_APROBADO_INVITACIONES: definido en catálogo, NO habilitado productivamente.
 */

export const EVENTOS = Object.freeze({
  REQUERIMIENTO_REGISTRADO: 'REQUERIMIENTO_REGISTRADO',
  REQUERIMIENTO_ENVIADO_EVALUACION: 'REQUERIMIENTO_ENVIADO_EVALUACION',
  EVALUACION_APROBADA: 'EVALUACION_APROBADA',
  EVALUACION_OBSERVADA: 'EVALUACION_OBSERVADA',
  DEC_APROBADO: 'DEC_APROBADO',
  DEC_OBSERVADA: 'DEC_OBSERVADA',
  PROGRAMACION_APROBADA: 'PROGRAMACION_APROBADA',
  PROGRAMACION_OBSERVADA: 'PROGRAMACION_OBSERVADA',
  COORDINACION_CM_APROBADA: 'COORDINACION_CM_APROBADA',
  COORDINACION_CM_OBSERVADA: 'COORDINACION_CM_OBSERVADA',
  COORDINACION_CM_SUBSANADA: 'COORDINACION_CM_SUBSANADA',
  COORDINACION_CM_ASIGNADA: 'COORDINACION_CM_ASIGNADA',
  SOLICITUD_COTIZACION_CREADA: 'SOLICITUD_COTIZACION_CREADA',
  INVITACION_ENVIADA: 'INVITACION_ENVIADA',
  REINVITACION_ENVIADA: 'REINVITACION_ENVIADA',
  INVITACIONES_OBSERVADA: 'INVITACIONES_OBSERVADA',
  OBSERVACION_SUBSANADA: 'OBSERVACION_SUBSANADA',
  COTIZACION_PRESENTADA: 'COTIZACION_PRESENTADA',
  COTIZACIONES_DERIVADAS_VALIDACION: 'COTIZACIONES_DERIVADAS_VALIDACION',
  COTIZACIONES_INVALIDAS_DEVUELTAS: 'COTIZACIONES_INVALIDAS_DEVUELTAS',
  LOCACION_APROBADA_RECEPCION: 'LOCACION_APROBADA_RECEPCION',
  VIATICO_APROBADO_INVITACIONES: 'VIATICO_APROBADO_INVITACIONES',
  VALIDACION_COMPLETADA: 'VALIDACION_COMPLETADA',
  VALIDACION_DEVUELTA: 'VALIDACION_DEVUELTA',
  CUADRO_GENERADO: 'CUADRO_GENERADO',
  CUADRO_DERIVADO_COORDINACION: 'CUADRO_DERIVADO_COORDINACION',
  CUADRO_APROBADO_COORDINACION: 'CUADRO_APROBADO_COORDINACION',
  CUADRO_OBSERVADO_COORDINACION: 'CUADRO_OBSERVADO_COORDINACION',
  CUADRO_DERIVADO_DEC: 'CUADRO_DERIVADO_DEC',
  CUADRO_APROBADO_DEC: 'CUADRO_APROBADO_DEC',
  CUADRO_OBSERVADO_DEC: 'CUADRO_OBSERVADO_DEC',
  CCP_REGISTRADA: 'CCP_REGISTRADA',
  ORDEN_REGISTRADA: 'ORDEN_REGISTRADA',
  ORDEN_NOTIFICADA: 'ORDEN_NOTIFICADA',
  ORDEN_CONFIRMADA_PROVEEDOR: 'ORDEN_CONFIRMADA_PROVEEDOR',
  ORDEN_DERIVADA_EJECUCION: 'ORDEN_DERIVADA_EJECUCION',
  ENTREGA_RECIBIDA: 'ENTREGA_RECIBIDA',
  ENTREGABLE_RECIBIDO: 'ENTREGABLE_RECIBIDO',
  CONFORMIDAD_REGISTRADA: 'CONFORMIDAD_REGISTRADA',
  AMPLIACION_REGISTRADA: 'AMPLIACION_REGISTRADA',
  ORDEN_OBSERVADA: 'ORDEN_OBSERVADA',
  ORDEN_ANULADA: 'ORDEN_ANULADA',
  ORDEN_RESUELTA: 'ORDEN_RESUELTA',
  EXPEDIENTE_DERIVADO_PAGO: 'EXPEDIENTE_DERIVADO_PAGO',
  EXPEDIENTE_FINALIZADO: 'EXPEDIENTE_FINALIZADO',
});

export const EVENTOS_LIST = Object.freeze(Object.values(EVENTOS));

/** Meta básica por evento: si cambia ubicación o es interno del dominio. */
const EVENTO_META = Object.freeze({
  [EVENTOS.REQUERIMIENTO_REGISTRADO]: Object.freeze({ codigo: EVENTOS.REQUERIMIENTO_REGISTRADO, cambiaUbicacion: false, tipo: 'CREACION' }),
  [EVENTOS.REQUERIMIENTO_ENVIADO_EVALUACION]: Object.freeze({ codigo: EVENTOS.REQUERIMIENTO_ENVIADO_EVALUACION, cambiaUbicacion: true, tipo: 'DERIVACION' }),
  [EVENTOS.EVALUACION_APROBADA]: Object.freeze({ codigo: EVENTOS.EVALUACION_APROBADA, cambiaUbicacion: true, tipo: 'APROBACION' }),
  [EVENTOS.EVALUACION_OBSERVADA]: Object.freeze({ codigo: EVENTOS.EVALUACION_OBSERVADA, cambiaUbicacion: false, tipo: 'DEVOLUCION' }),
  [EVENTOS.DEC_APROBADO]: Object.freeze({ codigo: EVENTOS.DEC_APROBADO, cambiaUbicacion: true, tipo: 'APROBACION' }),
  [EVENTOS.DEC_OBSERVADA]: Object.freeze({ codigo: EVENTOS.DEC_OBSERVADA, cambiaUbicacion: false, tipo: 'DEVOLUCION' }),
  [EVENTOS.PROGRAMACION_APROBADA]: Object.freeze({ codigo: EVENTOS.PROGRAMACION_APROBADA, cambiaUbicacion: true, tipo: 'APROBACION' }),
  [EVENTOS.PROGRAMACION_OBSERVADA]: Object.freeze({ codigo: EVENTOS.PROGRAMACION_OBSERVADA, cambiaUbicacion: false, tipo: 'DEVOLUCION' }),
  [EVENTOS.COORDINACION_CM_APROBADA]: Object.freeze({ codigo: EVENTOS.COORDINACION_CM_APROBADA, cambiaUbicacion: true, tipo: 'APROBACION' }),
  [EVENTOS.COORDINACION_CM_OBSERVADA]: Object.freeze({
    codigo: EVENTOS.COORDINACION_CM_OBSERVADA,
    cambiaUbicacion: false,
    tipo: 'DEVOLUCION',
    define: ['estado_destino', 'etapa_destino', 'responsable_destino', 'quien_subsana', 'trazabilidad', 'idempotencia'],
  }),
  [EVENTOS.COORDINACION_CM_SUBSANADA]: Object.freeze({ codigo: EVENTOS.COORDINACION_CM_SUBSANADA, cambiaUbicacion: false, tipo: 'SUBSANACION' }),
  [EVENTOS.COORDINACION_CM_ASIGNADA]: Object.freeze({ codigo: EVENTOS.COORDINACION_CM_ASIGNADA, cambiaUbicacion: false, tipo: 'ASIGNACION' }),
  [EVENTOS.SOLICITUD_COTIZACION_CREADA]: Object.freeze({ codigo: EVENTOS.SOLICITUD_COTIZACION_CREADA, cambiaUbicacion: false, tipo: 'DOMINIO' }),
  [EVENTOS.INVITACION_ENVIADA]: Object.freeze({ codigo: EVENTOS.INVITACION_ENVIADA, cambiaUbicacion: false, tipo: 'DOMINIO' }),
  [EVENTOS.REINVITACION_ENVIADA]: Object.freeze({ codigo: EVENTOS.REINVITACION_ENVIADA, cambiaUbicacion: false, tipo: 'DOMINIO' }),
  [EVENTOS.INVITACIONES_OBSERVADA]: Object.freeze({ codigo: EVENTOS.INVITACIONES_OBSERVADA, cambiaUbicacion: false, tipo: 'DEVOLUCION' }),
  [EVENTOS.OBSERVACION_SUBSANADA]: Object.freeze({ codigo: EVENTOS.OBSERVACION_SUBSANADA, cambiaUbicacion: false, tipo: 'SUBSANACION' }),
  [EVENTOS.COTIZACION_PRESENTADA]: Object.freeze({ codigo: EVENTOS.COTIZACION_PRESENTADA, cambiaUbicacion: true, tipo: 'PORTAL', primeraCotizacionMueve: true }),
  [EVENTOS.COTIZACIONES_DERIVADAS_VALIDACION]: Object.freeze({ codigo: EVENTOS.COTIZACIONES_DERIVADAS_VALIDACION, cambiaUbicacion: true, tipo: 'DERIVACION' }),
  [EVENTOS.COTIZACIONES_INVALIDAS_DEVUELTAS]: Object.freeze({ codigo: EVENTOS.COTIZACIONES_INVALIDAS_DEVUELTAS, cambiaUbicacion: true, tipo: 'DEVOLUCION' }),
  [EVENTOS.LOCACION_APROBADA_RECEPCION]: Object.freeze({ codigo: EVENTOS.LOCACION_APROBADA_RECEPCION, cambiaUbicacion: true, tipo: 'INTERNO' }),
  [EVENTOS.VIATICO_APROBADO_INVITACIONES]: Object.freeze({ codigo: EVENTOS.VIATICO_APROBADO_INVITACIONES, cambiaUbicacion: true, tipo: 'APROBACION', flag: 'WORKFLOW_ENGINE_VIATICOS' }),
  [EVENTOS.VALIDACION_COMPLETADA]: Object.freeze({ codigo: EVENTOS.VALIDACION_COMPLETADA, cambiaUbicacion: true, tipo: 'APROBACION' }),
  [EVENTOS.VALIDACION_DEVUELTA]: Object.freeze({ codigo: EVENTOS.VALIDACION_DEVUELTA, cambiaUbicacion: false, tipo: 'DEVOLUCION' }),
  [EVENTOS.CUADRO_GENERADO]: Object.freeze({ codigo: EVENTOS.CUADRO_GENERADO, cambiaUbicacion: false, tipo: 'DOMINIO' }),
  [EVENTOS.CUADRO_DERIVADO_COORDINACION]: Object.freeze({ codigo: EVENTOS.CUADRO_DERIVADO_COORDINACION, cambiaUbicacion: false, tipo: 'DOMINIO' }),
  [EVENTOS.CUADRO_APROBADO_COORDINACION]: Object.freeze({ codigo: EVENTOS.CUADRO_APROBADO_COORDINACION, cambiaUbicacion: false, tipo: 'DOMINIO' }),
  [EVENTOS.CUADRO_OBSERVADO_COORDINACION]: Object.freeze({ codigo: EVENTOS.CUADRO_OBSERVADO_COORDINACION, cambiaUbicacion: false, tipo: 'DEVOLUCION' }),
  [EVENTOS.CUADRO_DERIVADO_DEC]: Object.freeze({ codigo: EVENTOS.CUADRO_DERIVADO_DEC, cambiaUbicacion: false, tipo: 'DOMINIO' }),
  [EVENTOS.CUADRO_APROBADO_DEC]: Object.freeze({ codigo: EVENTOS.CUADRO_APROBADO_DEC, cambiaUbicacion: true, tipo: 'APROBACION' }),
  [EVENTOS.CUADRO_OBSERVADO_DEC]: Object.freeze({ codigo: EVENTOS.CUADRO_OBSERVADO_DEC, cambiaUbicacion: false, tipo: 'DEVOLUCION' }),
  [EVENTOS.CCP_REGISTRADA]: Object.freeze({ codigo: EVENTOS.CCP_REGISTRADA, cambiaUbicacion: true, tipo: 'DOMINIO' }),
  [EVENTOS.ORDEN_REGISTRADA]: Object.freeze({ codigo: EVENTOS.ORDEN_REGISTRADA, cambiaUbicacion: false, tipo: 'DOMINIO' }),
  [EVENTOS.ORDEN_NOTIFICADA]: Object.freeze({ codigo: EVENTOS.ORDEN_NOTIFICADA, cambiaUbicacion: false, tipo: 'DOMINIO' }),
  [EVENTOS.ORDEN_CONFIRMADA_PROVEEDOR]: Object.freeze({ codigo: EVENTOS.ORDEN_CONFIRMADA_PROVEEDOR, cambiaUbicacion: false, tipo: 'PORTAL' }),
  [EVENTOS.ORDEN_DERIVADA_EJECUCION]: Object.freeze({ codigo: EVENTOS.ORDEN_DERIVADA_EJECUCION, cambiaUbicacion: true, tipo: 'DERIVACION' }),
  [EVENTOS.ENTREGA_RECIBIDA]: Object.freeze({ codigo: EVENTOS.ENTREGA_RECIBIDA, cambiaUbicacion: false, tipo: 'INTERNO' }),
  [EVENTOS.ENTREGABLE_RECIBIDO]: Object.freeze({ codigo: EVENTOS.ENTREGABLE_RECIBIDO, cambiaUbicacion: false, tipo: 'INTERNO' }),
  [EVENTOS.CONFORMIDAD_REGISTRADA]: Object.freeze({ codigo: EVENTOS.CONFORMIDAD_REGISTRADA, cambiaUbicacion: false, tipo: 'DOMINIO' }),
  [EVENTOS.AMPLIACION_REGISTRADA]: Object.freeze({ codigo: EVENTOS.AMPLIACION_REGISTRADA, cambiaUbicacion: false, tipo: 'DOMINIO' }),
  [EVENTOS.ORDEN_OBSERVADA]: Object.freeze({ codigo: EVENTOS.ORDEN_OBSERVADA, cambiaUbicacion: false, tipo: 'DEVOLUCION' }),
  [EVENTOS.ORDEN_ANULADA]: Object.freeze({ codigo: EVENTOS.ORDEN_ANULADA, cambiaUbicacion: false, tipo: 'ANULACION' }),
  [EVENTOS.ORDEN_RESUELTA]: Object.freeze({ codigo: EVENTOS.ORDEN_RESUELTA, cambiaUbicacion: false, tipo: 'DOMINIO' }),
  [EVENTOS.EXPEDIENTE_DERIVADO_PAGO]: Object.freeze({ codigo: EVENTOS.EXPEDIENTE_DERIVADO_PAGO, cambiaUbicacion: true, tipo: 'DERIVACION' }),
  [EVENTOS.EXPEDIENTE_FINALIZADO]: Object.freeze({ codigo: EVENTOS.EXPEDIENTE_FINALIZADO, cambiaUbicacion: true, tipo: 'FINALIZACION' }),
});

export function esEventoValido(codigo) {
  return Object.prototype.hasOwnProperty.call(EVENTOS, codigo);
}

export function getEventoMeta(codigo) {
  return esEventoValido(codigo) ? EVENTO_META[codigo] : null;
}

export function eventoCambiaUbicacion(codigo) {
  return getEventoMeta(codigo)?.cambiaUbicacion === true;
}

export default {
  EVENTOS,
  EVENTOS_LIST,
  esEventoValido,
  getEventoMeta,
  eventoCambiaUbicacion,
};